const avatarPortraits = <String, ({String name, String asset})>{
  'portrait:dark_hair_boy': (
    name: '棕发小哥',
    asset: 'assets/avatars/dark_hair_boy.webp',
  ),
  'portrait:brown_hair_boy': (
    name: '皮衣墨镜男生',
    asset: 'assets/avatars/brown_hair_boy.webp',
  ),
  'portrait:basketball_boy': (
    name: '篮球男生',
    asset: 'assets/avatars/basketball_boy.webp',
  ),
  'portrait:navy_suit_man': (
    name: '西装眼镜男生',
    asset: 'assets/avatars/navy_suit_man.webp',
  ),
  'portrait:white_robed_swordsman': (
    name: '白衣剑客',
    asset: 'assets/avatars/white_robed_swordsman.webp',
  ),
  'portrait:brown_hair_girl': (
    name: '棕发女生',
    asset: 'assets/avatars/brown_hair_girl.webp',
  ),
  'portrait:pink_hair_girl': (
    name: '粉发女孩',
    asset: 'assets/avatars/pink_hair_girl.webp',
  ),
  'portrait:blonde_ponytail_girl': (
    name: '金发马尾女生',
    asset: 'assets/avatars/blonde_ponytail_girl.webp',
  ),
  'portrait:silver_hair_girl': (
    name: '银发女生',
    asset: 'assets/avatars/silver_hair_girl.webp',
  ),
  'portrait:golden_princess': (
    name: '古风公主',
    asset: 'assets/avatars/golden_princess.webp',
  ),
  'portrait:blue_cat': (name: '蓝帽猫咪', asset: 'assets/avatars/blue_cat.webp'),
  'portrait:shiba_inu': (name: '柴犬', asset: 'assets/avatars/shiba_inu.webp'),
  'portrait:fox': (name: '小狐狸', asset: 'assets/avatars/fox.webp'),
  'portrait:lynx': (name: '猞猁', asset: 'assets/avatars/lynx_yawning.webp'),
  'portrait:raccoon': (name: '浣熊', asset: 'assets/avatars/raccoon.webp'),
  'portrait:skunk': (name: '臭鼬', asset: 'assets/avatars/skunk_thumbs_down.webp'),
  'portrait:panda': (name: '大熊猫', asset: 'assets/avatars/panda.webp'),
  'portrait:polar_bear': (name: '白熊', asset: 'assets/avatars/polar_bear.webp'),
  'portrait:lion': (name: '小狮子', asset: 'assets/avatars/lion.webp'),
  'portrait:baby_tiger': (name: '小老虎', asset: 'assets/avatars/baby_tiger.webp'),
  'portrait:schnauzer': (name: '雪纳瑞', asset: 'assets/avatars/schnauzer.webp'),
  'portrait:capybara': (name: '水豚', asset: 'assets/avatars/capybara.webp'),
  'portrait:lizard': (name: '树袋熊', asset: 'assets/avatars/koala.webp'),
  'portrait:kangaroo': (name: '袋鼠', asset: 'assets/avatars/kangaroo.webp'),
  'portrait:monkey': (name: '猴子', asset: 'assets/avatars/monkey.webp'),
  'portrait:hippo': (name: '河马', asset: 'assets/avatars/hippo_drooling.webp'),
  'portrait:rhino': (name: '犀牛', asset: 'assets/avatars/rhino.webp'),
  'portrait:buffalo': (name: '美洲野牛', asset: 'assets/avatars/buffalo_italian.webp'),
  'portrait:camel': (name: '骆驼', asset: 'assets/avatars/camel.webp'),
  'portrait:moose': (name: '驼鹿', asset: 'assets/avatars/moose_sweat_smile.webp'),
  'portrait:alpaca': (name: '羊驼', asset: 'assets/avatars/alpaca.webp'),
  'portrait:baby_elephant': (
    name: '小象',
    asset: 'assets/avatars/baby_elephant.webp',
  ),
  'portrait:goat': (name: '山羊', asset: 'assets/avatars/goat.webp'),
  'portrait:hedgehog': (name: '刺猬', asset: 'assets/avatars/hedgehog.webp'),
  'portrait:hamster': (name: '仓鼠', asset: 'assets/avatars/hamster.webp'),
  'portrait:wild_rabbit': (name: '坏野兔', asset: 'assets/avatars/wild_rabbit.webp'),
  'portrait:chitu_horse': (
    name: '赤兔马',
    asset: 'assets/avatars/chitu_horse.webp',
  ),
  'portrait:giraffe': (name: '长颈鹿', asset: 'assets/avatars/giraffe.webp'),
  'portrait:magician_pig': (
    name: '魔术师小猪',
    asset: 'assets/avatars/magician_pig.webp',
  ),
  'portrait:duck': (name: '小鸭子', asset: 'assets/avatars/duck.webp'),
  'portrait:penguin': (name: '企鹅', asset: 'assets/avatars/penguin.webp'),
  'portrait:turkey': (name: '火鸡', asset: 'assets/avatars/turkey.webp'),
  'portrait:toucan': (name: '巨嘴鸟', asset: 'assets/avatars/toucan.webp'),
  'portrait:owl': (name: '猫头鹰', asset: 'assets/avatars/owl.webp'),
  'portrait:owl_turned': (
    name: '转头猫头鹰',
    asset: 'assets/avatars/owl_turned.webp',
  ),
  'portrait:parrot': (name: '鹦鹉', asset: 'assets/avatars/parrot.webp'),
  'portrait:frog': (name: '小青蛙', asset: 'assets/avatars/frog.webp'),
  'portrait:turtle': (name: '海龟', asset: 'assets/avatars/turtle.webp'),
  'portrait:yellow_gecko': (
    name: '鹅黄色守宫',
    asset: 'assets/avatars/yellow_gecko.webp',
  ),
  'portrait:frilled_lizard': (
    name: '伞蜥',
    asset: 'assets/avatars/frilled_lizard.webp',
  ),
  'portrait:snail': (name: '蜗牛', asset: 'assets/avatars/snail.webp'),
  'portrait:baby_trex': (name: '小霸王龙', asset: 'assets/avatars/baby_trex.webp'),
  'portrait:crocodile': (name: '鳄鱼', asset: 'assets/avatars/crocodile.webp'),
  'portrait:seal': (name: '小海豹', asset: 'assets/avatars/seal_starfish.webp'),
  'portrait:pink_dolphin': (
    name: '粉色海豚',
    asset: 'assets/avatars/pink_dolphin.webp',
  ),
  'portrait:shark': (name: '鲨鱼', asset: 'assets/avatars/shark.webp'),
  'portrait:pufferfish': (name: '河豚', asset: 'assets/avatars/pufferfish.webp'),
  'portrait:octopus': (name: '比心章鱼', asset: 'assets/avatars/octopus.webp'),
  'portrait:sunflower': (name: '向日葵', asset: 'assets/avatars/sunflower.webp'),
  'portrait:cactus': (name: '小仙人掌', asset: 'assets/avatars/cactus.webp'),
  'portrait:eggplant': (name: '茄子', asset: 'assets/avatars/eggplant.webp'),
  'portrait:tomato': (name: '番茄', asset: 'assets/avatars/tomato_tongue_out.webp'),
  'portrait:avocado': (name: '牛油果', asset: 'assets/avatars/avocado_reclining.webp'),
  'portrait:shiitake': (name: '香菇', asset: 'assets/avatars/shiitake.webp'),
  'portrait:toast': (name: '吐司', asset: 'assets/avatars/toast.webp'),
  'portrait:dumpling': (name: '饺子', asset: 'assets/avatars/dumpling.webp'),
  'portrait:double_scoop_ice_cream': (
    name: '双球冰淇淋',
    asset: 'assets/avatars/double_scoop_ice_cream.webp',
  ),
  'portrait:lollipop': (name: '棒棒糖', asset: 'assets/avatars/lollipop.webp'),
  'portrait:red_dragon_fruit': (
    name: '红心火龙果',
    asset: 'assets/avatars/red_dragon_fruit_indignant.webp',
  ),
  'portrait:pumpkin': (name: '南瓜头', asset: 'assets/avatars/pumpkin.webp'),
  'portrait:ghost': (name: '幽灵', asset: 'assets/avatars/ghost.webp'),
  'portrait:little_robot': (
    name: '小机器人',
    asset: 'assets/avatars/little_robot.webp',
  ),
  'portrait:saturn': (name: '土星', asset: 'assets/avatars/saturn.webp'),
  'portrait:sunglasses_bee': (
    name: '墨镜蜜蜂',
    asset: 'assets/avatars/sunglasses_bee.webp',
  ),
};

// Keep wide features inside the circle; portrait bodies align to its bottom.
const avatarPortraitScales = <String, double>{
  'portrait:lollipop': .9,
  'portrait:avocado': .9,
  'portrait:kangaroo': 1.12,
  'portrait:snail': .84,
  'portrait:saturn': .88,
  'portrait:sunglasses_bee': .9,
  'portrait:baby_tiger': .9,
  'portrait:schnauzer': .9,
  'portrait:dumpling': .9,
  'portrait:double_scoop_ice_cream': .92,
};
