class QuickReplyOption {
  const QuickReplyOption({
    required this.key,
    required this.emoji,
    required this.label,
    required this.text,
  });

  final String key;
  final String emoji;
  final String label;
  final String text;
}

const quickReplyOptions = [
  QuickReplyOption(key: 'ill', emoji: '😷', label: '生病', text: '😷 生病'),
  QuickReplyOption(key: 'face', emoji: '🙂', label: '人脸', text: '🙂 人脸'),
  QuickReplyOption(key: 'fireworks', emoji: '🎆', label: '烟花', text: '🎆 烟花'),
  QuickReplyOption(key: 't_shirt', emoji: '👕', label: 'T恤', text: '👕 T恤'),
  QuickReplyOption(key: 'dress', emoji: '👗', label: '连衣裙', text: '👗 连衣裙'),
  QuickReplyOption(key: 'necktie', emoji: '👔', label: '正装', text: '👔 正装'),
  QuickReplyOption(key: 'jeans', emoji: '👖', label: '牛仔裤', text: '👖 牛仔裤'),
  QuickReplyOption(key: 'coat', emoji: '🧥', label: '外套', text: '🧥 外套'),
  QuickReplyOption(key: 'lab_coat', emoji: '🥼', label: '白大褂', text: '🥼 白大褂'),
  QuickReplyOption(key: 'safety_vest', emoji: '🦺', label: '马甲', text: '🦺 马甲'),
  QuickReplyOption(key: 'kimono', emoji: '👘', label: '和服', text: '👘 和服'),
  QuickReplyOption(
    key: 'running_shoe',
    emoji: '👟',
    label: '运动鞋',
    text: '👟 运动鞋',
  ),
  QuickReplyOption(key: 'high_heel', emoji: '👠', label: '高跟鞋', text: '👠 高跟鞋'),
  QuickReplyOption(key: 'cap', emoji: '🧢', label: '帽子', text: '🧢 帽子'),
  QuickReplyOption(key: 'crown', emoji: '👑', label: '皇冠', text: '👑 皇冠'),
  QuickReplyOption(key: 'soccer', emoji: '⚽', label: '足球', text: '⚽ 足球'),
  QuickReplyOption(key: 'basketball', emoji: '🏀', label: '篮球', text: '🏀 篮球'),
  QuickReplyOption(key: 'tennis', emoji: '🎾', label: '网球', text: '🎾 网球'),
  QuickReplyOption(key: 'volleyball', emoji: '🏐', label: '排球', text: '🏐 排球'),
  QuickReplyOption(key: 'ping_pong', emoji: '🏓', label: '乒乓球', text: '🏓 乒乓球'),
  QuickReplyOption(key: 'badminton', emoji: '🏸', label: '羽毛球', text: '🏸 羽毛球'),
  QuickReplyOption(key: 'boxing', emoji: '🥊', label: '拳击', text: '🥊 拳击'),
  QuickReplyOption(key: 'swimming', emoji: '🏊', label: '游泳', text: '🏊 游泳'),
  QuickReplyOption(key: 'cycling', emoji: '🚴', label: '骑行', text: '🚴 骑行'),
  QuickReplyOption(key: 'running', emoji: '🏃', label: '跑步', text: '🏃 跑步'),
  QuickReplyOption(key: 'gaming', emoji: '🎮', label: '游戏', text: '🎮 游戏'),
  QuickReplyOption(key: 'singing', emoji: '🎤', label: '唱歌', text: '🎤 唱歌'),
  QuickReplyOption(key: 'cross_mark', emoji: '❌', label: '不行', text: '❌ 不行'),
  QuickReplyOption(key: 'warning', emoji: '⚠️', label: '注意', text: '⚠️ 注意'),
  QuickReplyOption(key: 'no_entry', emoji: '⛔', label: '停止', text: '⛔ 停止'),
  QuickReplyOption(key: 'prohibited', emoji: '🚫', label: '禁止', text: '🚫 禁止'),
  QuickReplyOption(key: 'exclamation', emoji: '❗', label: '重点', text: '❗ 重点'),
  QuickReplyOption(
    key: 'double_exclamation',
    emoji: '‼️',
    label: '强调',
    text: '‼️ 强调',
  ),
  QuickReplyOption(key: 'light_bulb', emoji: '💡', label: '灵感', text: '💡 灵感'),
  QuickReplyOption(key: 'recycle', emoji: '♻️', label: '循环', text: '♻️ 循环'),
  QuickReplyOption(key: 'repeat', emoji: '🔁', label: '再来', text: '🔁 再来'),
  QuickReplyOption(key: 'add', emoji: '➕', label: '加一个', text: '➕ 加一个'),
  QuickReplyOption(key: 'subtract', emoji: '➖', label: '减一个', text: '➖ 减一个'),
  QuickReplyOption(key: 'check_mark', emoji: '✔️', label: '确认', text: '✔️ 确认'),
  QuickReplyOption(key: 'lips', emoji: '💋', label: '嘴唇', text: '💋 嘴唇'),
  QuickReplyOption(
    key: 'kissing_face',
    emoji: '😗',
    label: '亲嘴',
    text: '😗 亲嘴',
  ),
  QuickReplyOption(
    key: 'pinched_fingers',
    emoji: '🤌',
    label: '拿捏',
    text: '🤌 拿捏',
  ),
  QuickReplyOption(
    key: 'pinching_hand',
    emoji: '🤏',
    label: '一点点',
    text: '🤏 一点点',
  ),
  QuickReplyOption(
    key: 'finger_heart',
    emoji: '🫰',
    label: '比心',
    text: '🫰 比心',
  ),
  QuickReplyOption(
    key: 'crossed_fingers',
    emoji: '🤞',
    label: '好运',
    text: '🤞 好运',
  ),
  QuickReplyOption(key: 'vulcan', emoji: '🖖', label: '你好', text: '🖖 你好'),
  QuickReplyOption(
    key: 'love_you_gesture',
    emoji: '🤟',
    label: '爱你',
    text: '🤟 爱你',
  ),
  QuickReplyOption(key: 'rock_on', emoji: '🤘', label: '摇滚', text: '🤘 摇滚'),
  QuickReplyOption(
    key: 'raised_hands',
    emoji: '🙌',
    label: '太棒了',
    text: '🙌 太棒了',
  ),
  QuickReplyOption(key: 'call_me', emoji: '🤙', label: '联系我', text: '🤙 联系我'),
  QuickReplyOption(key: 'black_face', emoji: '🌚', label: '黑脸', text: '🌚 黑脸'),
  QuickReplyOption(key: 'devil', emoji: '😈', label: '坏笑', text: '😈 坏笑'),
  QuickReplyOption(
    key: 'angry_devil',
    emoji: '👿',
    label: '小恶魔',
    text: '👿 小恶魔',
  ),
  QuickReplyOption(key: 'clown', emoji: '🤡', label: '小丑', text: '🤡 小丑'),
  QuickReplyOption(key: 'money_face', emoji: '🤑', label: '发财', text: '🤑 发财'),
  QuickReplyOption(key: 'nerd', emoji: '🤓', label: '学霸', text: '🤓 学霸'),
  QuickReplyOption(key: 'monocle', emoji: '🧐', label: '审视', text: '🧐 审视'),
  QuickReplyOption(key: 'grimace', emoji: '😬', label: '龇牙', text: '😬 龇牙'),
  QuickReplyOption(key: 'silent', emoji: '😶', label: '沉默', text: '😶 沉默'),
  QuickReplyOption(
    key: 'fog_face',
    emoji: '😶‍🌫️',
    label: '迷糊',
    text: '😶‍🌫️ 迷糊',
  ),
  QuickReplyOption(key: 'dotted_face', emoji: '🫥', label: '隐身', text: '🫥 隐身'),
  QuickReplyOption(key: 'zany', emoji: '🤪', label: '疯狂', text: '🤪 疯狂'),
  QuickReplyOption(key: 'tongue_wink', emoji: '😜', label: '调皮', text: '😜 调皮'),
  QuickReplyOption(key: 'yummy', emoji: '😋', label: '好吃', text: '😋 好吃'),
  QuickReplyOption(key: 'angel', emoji: '😇', label: '天使', text: '😇 天使'),
  QuickReplyOption(key: 'relieved', emoji: '😌', label: '放心', text: '😌 放心'),
  QuickReplyOption(key: 'pensive', emoji: '😔', label: '失落', text: '😔 失落'),
  QuickReplyOption(
    key: 'disappointed',
    emoji: '😞',
    label: '失望',
    text: '😞 失望',
  ),
  QuickReplyOption(key: 'confounded', emoji: '😖', label: '难受', text: '😖 难受'),
  QuickReplyOption(key: 'dizzy', emoji: '😵', label: '晕了', text: '😵 晕了'),
  QuickReplyOption(key: 'plus_one', emoji: '+1', label: '附议', text: '+1 附议'),
  QuickReplyOption(key: 'received', emoji: '👌', label: '收到', text: '👌 收到'),
  QuickReplyOption(key: 'like', emoji: '👍', label: '点赞', text: '👍 点赞'),
  QuickReplyOption(key: 'dislike', emoji: '👎', label: '点踩', text: '👎 点踩'),
  QuickReplyOption(key: 'dog', emoji: '🐶', label: '狗头', text: '🐶 狗头'),
  QuickReplyOption(key: 'love', emoji: '❤️', label: '喜欢', text: '❤️ 喜欢'),
  QuickReplyOption(key: 'laugh', emoji: '😂', label: '哈哈', text: '😂 哈哈'),
  QuickReplyOption(key: 'celebrate', emoji: '🎉', label: '庆祝', text: '🎉 庆祝'),
  QuickReplyOption(key: 'done', emoji: '✅', label: '完成', text: '✅ 完成'),
  QuickReplyOption(key: 'viewing', emoji: '👀', label: '在看', text: '👀 在看'),
  QuickReplyOption(key: 'question', emoji: '❓', label: '疑问', text: '❓ 有疑问'),
  QuickReplyOption(key: 'smile', emoji: '😊', label: '开心', text: '😊 开心'),
  QuickReplyOption(key: 'surprised', emoji: '😮', label: '惊讶', text: '😮 惊讶'),
  QuickReplyOption(key: 'sad', emoji: '😢', label: '难过', text: '😢 难过'),
  QuickReplyOption(key: 'angry', emoji: '😡', label: '生气', text: '😡 生气'),
  QuickReplyOption(key: 'thinking', emoji: '🤔', label: '思考', text: '🤔 思考'),
  QuickReplyOption(key: 'sweat', emoji: '😅', label: '尴尬', text: '😅 尴尬'),
  QuickReplyOption(key: 'speechless', emoji: '😑', label: '无语', text: '😑 无语'),
  QuickReplyOption(key: 'cool', emoji: '😎', label: '酷', text: '😎 酷'),
  QuickReplyOption(key: 'clap', emoji: '👏', label: '鼓掌', text: '👏 鼓掌'),
  QuickReplyOption(key: 'thanks', emoji: '🙏', label: '感谢', text: '🙏 感谢'),
  QuickReplyOption(key: 'strong', emoji: '💪', label: '加油', text: '💪 加油'),
  QuickReplyOption(key: 'fire', emoji: '🔥', label: '火热', text: '🔥 火热'),
  QuickReplyOption(key: 'hundred', emoji: '💯', label: '满分', text: '💯 满分'),
  QuickReplyOption(key: 'hug', emoji: '🤗', label: '抱抱', text: '🤗 抱抱'),
  QuickReplyOption(key: 'heart_eyes', emoji: '😍', label: '心动', text: '😍 心动'),
  QuickReplyOption(key: 'rainbow', emoji: '🌈', label: '彩虹', text: '🌈 彩虹'),
  QuickReplyOption(key: 'flower', emoji: '🌸', label: '送花', text: '🌸 送花'),
  QuickReplyOption(key: 'gift', emoji: '🎁', label: '礼物', text: '🎁 礼物'),
  QuickReplyOption(key: 'rocket', emoji: '🚀', label: '起飞', text: '🚀 起飞'),
  QuickReplyOption(key: 'coffee', emoji: '☕', label: '喝杯咖啡', text: '☕ 喝杯咖啡'),
  QuickReplyOption(key: 'diamond', emoji: '💎', label: '珍贵', text: '💎 珍贵'),
  QuickReplyOption(key: 'clover', emoji: '🍀', label: '好运', text: '🍀 好运'),
  QuickReplyOption(key: 'ice', emoji: '🧊', label: '冷静', text: '🧊 冷静'),
  QuickReplyOption(key: 'party', emoji: '🎊', label: '欢庆', text: '🎊 欢庆'),
  QuickReplyOption(
    key: 'bullseye',
    emoji: '🎯',
    label: '说到点上',
    text: '🎯 说到点上',
  ),
  QuickReplyOption(key: 'penguin', emoji: '🐧', label: '企鹅', text: '🐧 企鹅'),
  QuickReplyOption(key: 'cat', emoji: '🐱', label: '猫猫', text: '🐱 猫猫'),
  QuickReplyOption(key: 'unicorn', emoji: '🦄', label: '独角兽', text: '🦄 独角兽'),
  QuickReplyOption(key: 'ghost', emoji: '👻', label: '幽灵', text: '👻 幽灵'),
  QuickReplyOption(key: 'robot', emoji: '🤖', label: '机器人', text: '🤖 机器人'),
  QuickReplyOption(key: 'poop', emoji: '💩', label: '便便', text: '💩 便便'),
  QuickReplyOption(key: 'melon', emoji: '🍉', label: '吃瓜', text: '🍉 吃瓜'),
  QuickReplyOption(key: 'lemon', emoji: '🍋', label: '酸了', text: '🍋 酸了'),
  QuickReplyOption(key: 'beer', emoji: '🍺', label: '干杯', text: '🍺 干杯'),
  QuickReplyOption(
    key: 'broken_heart',
    emoji: '💔',
    label: '心碎',
    text: '💔 心碎',
  ),
  QuickReplyOption(
    key: 'wilted_flower',
    emoji: '🥀',
    label: '枯萎',
    text: '🥀 枯萎',
  ),
  QuickReplyOption(key: 'sleep', emoji: '💤', label: '困了', text: '💤 困了'),
  QuickReplyOption(key: 'sob', emoji: '😭', label: '大哭', text: '😭 大哭'),
  QuickReplyOption(key: 'touched', emoji: '🥹', label: '感动', text: '🥹 感动'),
  QuickReplyOption(key: 'eye_roll', emoji: '🙄', label: '白眼', text: '🙄 白眼'),
  QuickReplyOption(key: 'mind_blown', emoji: '🤯', label: '震惊', text: '🤯 震惊'),
  QuickReplyOption(key: 'salute', emoji: '🫡', label: '敬礼', text: '🫡 敬礼'),
  QuickReplyOption(key: 'handshake', emoji: '🤝', label: '握手', text: '🤝 握手'),
  QuickReplyOption(key: 'panda', emoji: '🐼', label: '熊猫', text: '🐼 熊猫'),
  QuickReplyOption(key: 'fox', emoji: '🦊', label: '狐狸', text: '🦊 狐狸'),
  QuickReplyOption(key: 'popcorn', emoji: '🍿', label: '看戏', text: '🍿 看戏'),
  QuickReplyOption(key: 'brain', emoji: '🧠', label: '聪明', text: '🧠 聪明'),
  QuickReplyOption(key: 'trophy', emoji: '🏆', label: '冠军', text: '🏆 冠军'),
  QuickReplyOption(key: 'heart_hands', emoji: '🫶', label: '比心', text: '🫶 比心'),
  QuickReplyOption(key: 'skull', emoji: '💀', label: '笑死', text: '💀 笑死'),
  QuickReplyOption(key: 'alien', emoji: '👽', label: '外星人', text: '👽 外星人'),
  QuickReplyOption(
    key: 'see_no_evil',
    emoji: '🙈',
    label: '没眼看',
    text: '🙈 没眼看',
  ),
  QuickReplyOption(key: 'shush', emoji: '🤫', label: '嘘', text: '🤫 嘘'),
  QuickReplyOption(key: 'zip_mouth', emoji: '🤐', label: '保密', text: '🤐 保密'),
  QuickReplyOption(key: 'yawn', emoji: '🥱', label: '打哈欠', text: '🥱 打哈欠'),
  QuickReplyOption(key: 'sick', emoji: '🤒', label: '不舒服', text: '🤒 不舒服'),
  QuickReplyOption(key: 'melting', emoji: '🫠', label: '融化', text: '🫠 融化'),
  QuickReplyOption(
    key: 'upside_down',
    emoji: '🙃',
    label: '倒着笑',
    text: '🙃 倒着笑',
  ),
  QuickReplyOption(key: 'wink', emoji: '😉', label: '眨眼', text: '😉 眨眼'),
  QuickReplyOption(key: 'wave', emoji: '👋', label: '挥手', text: '👋 挥手'),
  QuickReplyOption(key: 'fist_bump', emoji: '👊', label: '拳头', text: '👊 拳头'),
  QuickReplyOption(key: 'victory', emoji: '✌️', label: '耶', text: '✌️ 耶'),
  QuickReplyOption(key: 'point_up', emoji: '☝️', label: '注意', text: '☝️ 注意'),
  QuickReplyOption(key: 'writing', emoji: '✍️', label: '记下了', text: '✍️ 记下了'),
  QuickReplyOption(key: 'frog', emoji: '🐸', label: '青蛙', text: '🐸 青蛙'),
  QuickReplyOption(key: 'rabbit', emoji: '🐰', label: '兔兔', text: '🐰 兔兔'),
  QuickReplyOption(key: 'bear', emoji: '🐻', label: '小熊', text: '🐻 小熊'),
  QuickReplyOption(key: 'tiger', emoji: '🐯', label: '老虎', text: '🐯 老虎'),
  QuickReplyOption(key: 'dragon', emoji: '🐉', label: '龙', text: '🐉 龙'),
  QuickReplyOption(key: 'butterfly', emoji: '🦋', label: '蝴蝶', text: '🦋 蝴蝶'),
  QuickReplyOption(key: 'snail', emoji: '🐌', label: '慢慢来', text: '🐌 慢慢来'),
  QuickReplyOption(key: 'turtle', emoji: '🐢', label: '不着急', text: '🐢 不着急'),
  QuickReplyOption(key: 'shark', emoji: '🦈', label: '鲨鱼', text: '🦈 鲨鱼'),
  QuickReplyOption(key: 'pizza', emoji: '🍕', label: '披萨', text: '🍕 披萨'),
  QuickReplyOption(key: 'cake', emoji: '🎂', label: '生日快乐', text: '🎂 生日快乐'),
  QuickReplyOption(key: 'milk_tea', emoji: '🧋', label: '奶茶', text: '🧋 奶茶'),
  QuickReplyOption(key: 'cheers', emoji: '🥂', label: '庆功', text: '🥂 庆功'),
  QuickReplyOption(key: 'sparkles', emoji: '✨', label: '闪亮', text: '✨ 闪亮'),
  QuickReplyOption(key: 'bomb', emoji: '💣', label: '炸了', text: '💣 炸了'),
  QuickReplyOption(key: 'grin', emoji: '😀', label: '笑脸', text: '😀 笑脸'),
  QuickReplyOption(key: 'beaming', emoji: '😁', label: '灿烂', text: '😁 灿烂'),
  QuickReplyOption(
    key: 'rolling_laugh',
    emoji: '🤣',
    label: '笑翻',
    text: '🤣 笑翻',
  ),
  QuickReplyOption(key: 'kiss', emoji: '😘', label: '亲亲', text: '😘 亲亲'),
  QuickReplyOption(key: 'pleading', emoji: '🥺', label: '可怜', text: '🥺 可怜'),
  QuickReplyOption(key: 'sleepy', emoji: '😴', label: '睡着', text: '😴 睡着'),
  QuickReplyOption(key: 'good_night', emoji: '🌃', label: '晚安', text: '🌃 晚安'),
  QuickReplyOption(key: 'moon', emoji: '🌙', label: '月亮', text: '🌙 月亮'),
  QuickReplyOption(key: 'star', emoji: '⭐', label: '星星', text: '⭐ 星星'),
  QuickReplyOption(key: 'wish', emoji: '🌠', label: '许愿', text: '🌠 许愿'),
  QuickReplyOption(
    key: 'good_morning',
    emoji: '🌅',
    label: '早安',
    text: '🌅 早安',
  ),
  QuickReplyOption(key: 'sun', emoji: '☀️', label: '太阳', text: '☀️ 太阳'),
  QuickReplyOption(key: 'rose', emoji: '🌹', label: '玫瑰', text: '🌹 玫瑰'),
  QuickReplyOption(
    key: 'smiling_hearts',
    emoji: '🥰',
    label: '幸福',
    text: '🥰 幸福',
  ),
  QuickReplyOption(key: 'star_struck', emoji: '🤩', label: '崇拜', text: '🤩 崇拜'),
  QuickReplyOption(key: 'peeking', emoji: '🫣', label: '偷看', text: '🫣 偷看'),
  QuickReplyOption(key: 'giggle', emoji: '🤭', label: '偷笑', text: '🤭 偷笑'),
  QuickReplyOption(key: 'bee', emoji: '🐝', label: '蜜蜂', text: '🐝 蜜蜂'),
  QuickReplyOption(key: 'owl', emoji: '🦉', label: '猫头鹰', text: '🦉 猫头鹰'),
  QuickReplyOption(key: 'otter', emoji: '🦦', label: '水獭', text: '🦦 水獭'),
  QuickReplyOption(key: 'chick', emoji: '🐥', label: '小鸡', text: '🐥 小鸡'),
  QuickReplyOption(
    key: 'sparkling_heart',
    emoji: '💖',
    label: '闪亮的心',
    text: '💖 闪亮的心',
  ),
  QuickReplyOption(
    key: 'two_hearts',
    emoji: '💕',
    label: '两颗心',
    text: '💕 两颗心',
  ),
  QuickReplyOption(key: 'love_letter', emoji: '💌', label: '情书', text: '💌 情书'),
  QuickReplyOption(key: 'strawberry', emoji: '🍓', label: '草莓', text: '🍓 草莓'),
  QuickReplyOption(key: 'cherries', emoji: '🍒', label: '樱桃', text: '🍒 樱桃'),
  QuickReplyOption(key: 'chocolate', emoji: '🍫', label: '巧克力', text: '🍫 巧克力'),
  QuickReplyOption(key: 'ice_cream', emoji: '🍦', label: '冰淇淋', text: '🍦 冰淇淋'),
  QuickReplyOption(key: 'sunflower', emoji: '🌻', label: '向日葵', text: '🌻 向日葵'),
  QuickReplyOption(key: 'tulip', emoji: '🌷', label: '郁金香', text: '🌷 郁金香'),
  QuickReplyOption(key: 'daisy', emoji: '🌼', label: '雏菊', text: '🌼 雏菊'),
  QuickReplyOption(key: 'maple_leaf', emoji: '🍁', label: '枫叶', text: '🍁 枫叶'),
  QuickReplyOption(key: 'snowflake', emoji: '❄️', label: '雪花', text: '❄️ 雪花'),
  QuickReplyOption(key: 'proud', emoji: '😤', label: '不服', text: '😤 不服'),
  QuickReplyOption(key: 'scared', emoji: '😱', label: '惊恐', text: '😱 惊恐'),
  QuickReplyOption(key: 'nauseated', emoji: '🤢', label: '恶心', text: '🤢 恶心'),
  QuickReplyOption(key: 'drooling', emoji: '🤤', label: '馋了', text: '🤤 馋了'),
  QuickReplyOption(key: 'sneezing', emoji: '🤧', label: '感冒', text: '🤧 感冒'),
  QuickReplyOption(key: 'party_face', emoji: '🥳', label: '派对', text: '🥳 派对'),
];

final quickReplyOptionsByKey = {
  for (final option in quickReplyOptions) option.key: option,
};
