import 'package:sqflite/sqflite.dart';
import 'tool_summary_seeds.dart';

const toolCustomizationSchema = '''CREATE TABLE tool_customizations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  icon TEXT NOT NULL,
  title TEXT,
  description TEXT,
  summary TEXT,
  input_schema_json TEXT
)''';

Future<void> migrateToolCustomizationPrimaryKey(DatabaseExecutor db) async {
  await db.execute(
    'ALTER TABLE tool_customizations RENAME TO previous_tool_customizations',
  );
  await db.execute(toolCustomizationSchema);
  await db.execute('''INSERT INTO tool_customizations
    (name, icon, title, description, input_schema_json)
    SELECT name, icon, title, description, input_schema_json
    FROM previous_tool_customizations''');
  await db.execute('DROP TABLE previous_tool_customizations');
}

const toolNamesByDefaultIcon = <String, List<String>>{
  'forward': ['forwardMessage'],
  'recall': ['recallMessage'],
  'compose': ['createConversation'],
  'rename': ['renameConversation', 'renameGroupChat', 'renameProject'],
  'pin': ['setConversationPinned', 'readGroupPinnedMessage', 'pinGroupMessage'],
  'unpin': ['unpinGroupMessage'],
  'archive': ['setConversationArchived'],
  'delete': ['deleteConversation', 'deleteDocument'],
  'star': [
    'starMessage',
    'unstarMessage',
    'listStarredMessages',
    'listGroupFavorites',
    'addGroupFavorite',
    'removeGroupFavorite',
  ],
  'announcement': [
    'readGroupAnnouncement',
    'updateGroupAnnouncement',
    'dismissGroupNotice',
  ],
  'miniapp': [
    'readHtmlData',
    'updateHtmlData',
    'readHtmlProgram',
    'submitHtmlProgramEvent',
    'listHtmlApps',
    'readHtmlAppData',
    'writeHtmlAppData',
    'sendHtmlMessage',
    'readHtmlMessage',
    'readHtmlApp',
    'readHtmlAppTeam',
    'requestHtmlAppEdit',
    'manageHtmlAppTeam',
    'listHtmlAppEditRequests',
    'updateHtmlApp',
    'updateHtmlMessage',
    'listHtmlAppPublications',
    'readHtmlAppPublication',
    'publishHtmlApp',
    'updateHtmlAppPublication',
    'setHtmlAppIcon',
    'withdrawHtmlApp',
  ],
  'conversation': [
    'sleepChat',
    'pauseAutoReply',
    'resumeAutoReply',
    'submitInteractiveChoice',
    'finishCurrentAction',
    'finishCurrentSpeech',
    'sendInteractiveMessage',
    'clickInteractiveMessage',
    'readInteractiveMessage',
    'retryInteractiveCallback',
    'updateInteractiveMessage',
    'sendConversationMessage',
    'readMessage',
    'locateMessage',
    'sendQuickReply',
  ],
  'group': [
    'readGroupPersonalDetails',
    'updateGroupPersonalDetails',
    'setGroupAdministrators',
    'sendGroupMessage',
    'wakeGroupMember',
    'setGroupMemberMute',
    'pauseGroupAutoReply',
    'resumeGroupAutoReply',
    'sleepGroupChat',
    'listGroupChats',
    'readGroupMessages',
    'readGroupChat',
    'createGroupChat',
    'updateGroupChatMembers',
  ],
  'contacts': [
    'findContacts',
    'listFriends',
    'addFriend',
    'listAiContacts',
    'readAiContact',
    'readMyProfile',
    'updateMyProfile',
    'createAiContact',
    'updateAiContact',
    'deleteAiContact',
    'restoreAiContact',
  ],
  'model': [
    'getModelConfiguration',
    'openModelConfiguration',
    'listModelProviders',
    'configureModelProvider',
    'requestModelProviderKey',
    'listProviderModels',
    'checkModelProvider',
    'readDefaultModels',
    'updateDefaultModel',
  ],
  'balance': ['getModelBalance', 'openModelTopUp'],
  'memory': [
    'listMemories',
    'readMemory',
    'createMemory',
    'updateMemory',
    'deleteMemory',
    'prepareMemoryChanges',
    'applyMemoryChanges',
  ],
  'skill': [
    'searchSkills',
    'enableSkill',
    'disableSkill',
    'listSkills',
    'readSkill',
    'createSkill',
    'updateSkill',
    'deleteSkill',
    'installSkill',
    'uninstallSkill',
    'manageSkill',
    'runSkill',
  ],
  'task': [
    'runTask',
    'runSubagent',
    'createGoal',
    'getGoal',
    'updateGoal',
    'clearGoal',
    'createTaskList',
    'getTaskList',
    'updateTaskList',
    'scheduledTask',
    'createScheduledTask',
    'updateScheduledTask',
    'listScheduledTasks',
    'pauseScheduledTask',
    'resumeScheduledTask',
    'deleteScheduledTask',
  ],
  'question': ['askUser'],
  'search': [
    'searchTools',
    'loadTools',
    'searchWeb',
    'searchConversations',
    'searchMessages',
  ],
  'image-search': ['searchImages', 'generateImage'],
  'music': ['generateMusic'],
  'app-search': ['findApps', 'openAppPage', 'launchApp', 'startIntent'],
  'file': [
    'listProjectTree',
    'searchProjectText',
    'copyDocument',
    'moveDocument',
    'getDocumentFolders',
    'requestDocumentFolder',
    'searchFiles',
    'listFiles',
    'listDirectory',
    'createFolder',
    'listProjects',
    'createProject',
    'setProjectIcon',
    'setProjectPinned',
    'setCurrentConversationProject',
  ],
  'browser': ['readWebPage'],
  'calendar': ['setSourceDates'],
  'document': [
    'readAttachment',
    'readMessageAttachment',
    'readExecutionLogs',
    'readDocument',
    'readFile',
    'inspectLocalDatabase',
    'queryLocalDatabase',
    'readLocalDatabase',
    'writeTextFile',
    'replaceText',
    'applyTextPatch',
    'renameDocument',
  ],
  'create-file': ['createTextFile'],
  'share-file': ['shareFile', 'deliverFile'],
  'code': [
    'inspectAndroidApi',
    'readGitConfiguration',
    'updateGitConfiguration',
    'getProjectGitStatus',
    'getProjectGitDiff',
    'initializeProjectGit',
    'setProjectGitRemote',
    'commitProjectGit',
    'pullProjectGit',
    'pushProjectGit',
    'mergeProjectBranch',
    'checkoutProjectBranch',
  ],
  'terminal': [
    'shell',
    'executeShizuku',
    'executeAndroidScript',
    'runProjectCommand',
  ],
  'permission': ['requestShizukuAccess', 'requestAccessibilityAccess'],
  'device': [
    'getDeviceExtensions',
    'observeDevice',
    'waitForUi',
    'clickUiElement',
    'inputUiText',
    'scrollUiForward',
    'scrollUiBackward',
    'goBack',
    'goHome',
    'act',
    'tapScreen',
  ],
  'network': [
    'startNetworkCapture',
    'stopNetworkCapture',
    'readNetworkTraffic',
    'clearNetworkTraffic',
    'getNetworkState',
    'getNetworkEvents',
    'dnsLookup',
    'httpProbe',
    'tlsProbe',
  ],
  'camera': ['captureScreen'],
  'notification': ['getNotifications', 'sendNotification'],
  'settings': ['openSettings'],
  'clock': ['wait'],
  'brain': ['hideThinking', 'compactContext'],
  'automation': [
    'readRequestAdapters',
    'previewRequestAdapter',
    'saveRequestAdapter',
  ],
};

Future<void> seedToolCustomizations(DatabaseExecutor db) async {
  final batch = db.batch();
  for (final entry in toolNamesByDefaultIcon.entries) {
    for (final name in entry.value) {
      batch.insert('tool_customizations', {
        'name': name,
        'icon': 'skill:${entry.key}',
      });
    }
  }
  await batch.commit(noResult: true);
  await seedToolSummaries(db, toolNamesByDefaultIcon);
}

Future<void> seedToolSummaryDefaults(DatabaseExecutor db) =>
    seedToolSummaries(db, toolNamesByDefaultIcon);
