import 'package:sqflite/sqflite.dart';

Future<void> seedToolSummaries(
  DatabaseExecutor db,
  Map<String, List<String>> namesByIcon,
) async {
  final rows = await db.query('tool_customizations', columns: ['name']);
  final existing = rows.map((row) => row['name'] as String).toSet();
  final icons = {
    for (final entry in namesByIcon.entries)
      for (final name in entry.value) name: 'skill:${entry.key}',
  };
  final batch = db.batch();
  for (final entry in _summaries.entries) {
    if (existing.contains(entry.key)) {
      // An empty string is an intentional edit, not an unset default.
      batch.update(
        'tool_customizations',
        {'summary': entry.value},
        where: 'name = ? AND summary IS NULL',
        whereArgs: [entry.key],
      );
    } else {
      batch.insert('tool_customizations', {
        'name': entry.key,
        'icon': icons[entry.key]!,
        'summary': entry.value,
      });
    }
  }
  await batch.commit(noResult: true);
}

/// Discovery copy only; full descriptions and schemas remain authoritative when loaded.
/// These defaults are written at database creation or migration, never read by tools.
const _summaries = <String, String>{
  'setGroupAdministrators': '设置指定群聊的管理员，只有具备群管理权限的身份才能操作。',
  'dismissGroupNotice': '隐藏自己上下文中的当前群公告或置顶提示，不影响其他成员，也不删除原始内容；更新后的公告和新置顶仍会出现。',
  'sendHtmlMessage':
      '发送可交互的 HTML 小程序消息，用于自定义页面、图表、小游戏和复杂表单。支持直接提供 HTML 或从本地文件发布，可在聊天内展示或全屏运行。可指定有权访问的目标会话；创建前加载完整说明，了解页面桥接、数据、身份和权限约束。普通文字或原生投票不需要此工具。',
  'sendInteractiveMessage':
      '使用基于 Flutter 设计的 DSL 创建自定义原生界面，支持组件组合、字段、状态、绑定、条件显示、列表和底部弹层。标准业务优先使用专用工具。',
  'sendQuestion': '向指定成员发送原生问题，填写题目和选项即可，提交后回调答案。向当前用户澄清信息使用 askUser。',
  'sendPoll': '发起原生投票，配置选项、参与者、匿名和结果可见范围，自动提供投票与统计界面，无需编写 DSL。',
  'sendQuestionnaire': '发送原生问卷，配置题目、参与者和结果可见范围，自动提供分页填写与答案查看界面，无需编写 DSL。',
  'updateInteractiveMessage':
      '修改已有交互卡片的标题、正文、按钮、状态、统计和参与设置。用于更新或关闭已有活动，不另发重复卡片。先读取当前卡片，使用返回的消息标识和版本，遵守权限及已有参与数据的约束。',
  'searchTools':
      '按用途、名称或关键词查找工具，搜索匹配简述和完整说明，只返回候选简述。选择后用 loadTools 加载完整调用定义；搜索和加载均不代表授权或执行。',
  'loadTools':
      '按搜索结果中的准确工具名加载完整说明和参数，供后续模型调用。一次最多五个，只选当前工作需要的工具；加载不会执行工具，也不会授予权限。',
  'runSubagent': '委派独立子代理执行明确的子任务，并取得执行结果。适合可独立推进的工作，必须明确目标、范围和必要上下文。',
  'runTask': '创建或继续同一 AI 的工作任务，将连续执行过程组织到任务中；已有工作使用原任务继续。',
  'createGoal': '建立用户明确要求持续推进的目标，可设置 Token 预算；普通请求不能自行变成持续目标。',
  'clearGoal': '清除当前目标，结束该目标的持续推进。',
  'getGoal': '读取当前目标、进度、用时和预算状态。',
  'updateGoal': '更新当前目标的完成、暂停或阻塞状态，必须有实际进展或用户要求支持。',
  'createTaskList': '创建精简执行计划，将多步骤工作拆成可追踪的清单，不自动建立持续目标。',
  'getTaskList': '读取当前执行计划及各步骤状态。',
  'updateTaskList': '更新执行计划的步骤、说明和完成状态。',
  'readGroupPersonalDetails': '读取当前成员的群内个人资料和昵称。',
  'updateGroupPersonalDetails': '修改群内昵称等个人资料，遵守群成员管理权限。',
  'readMyProfile': '读取自己的 AI 联系人资料、名称和个性化设置。',
  'updateMyProfile': '修改自己的 AI 资料、简介或头像，不修改其他联系人。',
  'listHtmlApps': '查找可使用的小程序及其入口。',
  'readHtmlAppData': '读取小程序持久化数据，遵守当前用户和小程序的数据访问范围。',
  'writeHtmlAppData': '保存或修改小程序持久化数据，不绕过访问权限。',
  'readHtmlMessage': '读取已有 HTML 消息的内容和配置，用于检查或继续修改。',
  'readHtmlProgram': '读取小程序当前状态和可执行行动，以真实返回状态决定后续操作。',
  'readHtmlData': '读取 HTML 消息公开给当前身份的数据。',
  'updateHtmlData': '更新 HTML 消息的数据，遵守数据结构和访问约束。',
  'submitHtmlProgramEvent': '向小程序提交已定义事件，以当前真实身份参与行动。',
  'readHtmlApp': '读取小程序源码、配置和相关资料。',
  'readHtmlAppTeam': '查看小程序开发团队及成员权限。',
  'requestHtmlAppEdit': '申请修改小程序，供有权限的开发成员处理。',
  'manageHtmlAppTeam': '管理小程序开发团队的成员和协作权限。',
  'listHtmlAppEditRequests': '查看小程序的修改申请及处理状态。',
  'updateHtmlApp': '修改已存在的小程序源码或配置，保留其身份与数据关系。',
  'updateHtmlMessage': '更新已有 HTML 消息的页面内容，支持从本地源文件发布修改。',
  'listHtmlAppPublications': '查询小程序发布记录和可发布的应用。',
  'readHtmlAppPublication': '读取小程序发布状态、版本和发布资料。',
  'publishHtmlApp': '发布可复用的小程序到应用库，不公开某条消息中的私人状态。',
  'updateHtmlAppPublication': '发布已有小程序的新版本。',
  'setHtmlAppIcon': '设置小程序在应用库和入口中显示的图标。',
  'withdrawHtmlApp': '撤下已发布的小程序。',
  'findContacts': '按姓名或其他线索查找联系人，以返回结果确认身份。',
  'listFriends': '查看自己的好友列表，不等同于人类用户的好友列表。',
  'addFriend': '将确认身份的联系人添加为自己的好友。',
  'readExecutionLogs': '读取实际执行日志，排查模型请求、工具调用和运行错误。',
  'clickInteractiveMessage': '实际参与交互卡片，使用最新读取结果中的按钮和行动令牌提交选择。文字表态不等于提交。',
  'submitInteractiveChoice': '提交当前交互活动的选择，遵守当前身份与行动权限。',
  'finishCurrentAction': '完成当前交互行动并返回规定结果。',
  'finishCurrentSpeech': '结束当前发言阶段，遵守当前活动的发言规则。',
  'readInteractiveMessage': '读取交互卡片的当前状态、可选按钮、统计和行动令牌。先读取再操作，只返回当前身份可见的信息。',
  'retryInteractiveCallback': '重新处理明确指定的交互回调，不重复提交参与者选择。',
  'setQuestionnairePaused':
      '暂停或恢复自己发起的问卷收集，保留已有回答；回调通过 collectionEvent 区分暂停与完成。',
  'createConversation': '创建或打开与指定联系人的私聊，确认双方身份后使用。',
  'renameConversation': '修改指定会话或任务的名称。',
  'setConversationPinned': '设置或取消会话置顶。',
  'setConversationArchived': '归档或恢复指定任务。',
  'deleteConversation': '删除指定会话及关联内容，遵守破坏性操作确认要求。',
  'sendConversationMessage': '以自己的身份向指定私聊发送消息，可携带图片、引用和 Markdown 格式。',
  'openAppPage': '打开 Aurai 内的指定功能页面。',
  'locateMessage': '定位已知消息并打开其原始位置。',
  'forwardMessage': '转发可访问的已有消息，遵守原始消息的可见范围和授权。',
  'getModelConfiguration': '读取当前模型与服务配置，用于确认实际调用设置。',
  'listModelProviders': '列出已配置的模型供应商。',
  'configureModelProvider': '修改指定模型供应商的配置。',
  'requestModelProviderKey': '打开安全输入流程，请用户填写模型供应商密钥。',
  'listProviderModels': '获取指定供应商可用的模型列表。',
  'checkModelProvider': '检查指定模型服务的连接及请求是否正常。',
  'openModelConfiguration': '打开模型设置页面供用户查看或修改。',
  'sendGroupMessage': '以自己的身份向已加入的群发送一条完整消息，也可调整自己的接话状态。支持图片、引用、提及及明确的消息可见范围。',
  'wakeGroupMember': '唤醒指定群成员，按参数决定是否立即处理消息。',
  'setGroupMemberMute': '设置群成员禁言状态，需要相应群管理权限。',
  'pauseGroupAutoReply': '暂停指定群成员自动接话，不等同于群管理禁言。',
  'resumeGroupAutoReply': '恢复指定群成员自动接话。',
  'sleepGroupChat': '暂时等待后续群消息或指定时间后再查看群聊，不持续发送无意义回复。',
  'sleepChat': '当前私聊或任务中睡眠等待，到点继续；新消息可提前唤醒。',
  'pauseAutoReply': '暂停当前私聊或任务的自动接话，并取消定时唤醒。',
  'resumeAutoReply': '恢复当前私聊或任务的自动接话。',
  'hideThinking': '隐藏当前回复的思考展示，不改变实际执行权限。',
  'compactContext': '整理较长的当前执行上下文，保留继续任务所需的信息。',
  'starMessage': '收藏可访问的消息，明确收藏属于自己还是人类用户。',
  'unstarMessage': '取消指定收藏，不删除原消息。',
  'listStarredMessages': '查看指定收藏所属人的收藏消息。',
  'sendQuickReply': '在原消息下添加快捷回应标签或表情，不发送普通聊天短句。',
  'recallMessage': '撤回有权撤回的消息，并处理其相关引用与记录。',
  'listGroupChats': '查询自己加入的群聊，确认目标群后再读取或发送。',
  'readMessage': '读取已知消息的原始内容和可见元数据。',
  'readMessageAttachment': '读取历史消息中实际存在的附件。',
  'readGroupMessages': '分页读取自己所在群的历史消息，只返回当前身份可见内容。',
  'readGroupChat': '读取群资料、成员和当前群状态。',
  'readGroupPinnedMessage': '读取群聊置顶消息。',
  'pinGroupMessage': '将指定群消息置顶，遵守群管理权限。',
  'unpinGroupMessage': '取消指定群消息置顶。',
  'listGroupFavorites': '查看群聊中的标记消息。',
  'addGroupFavorite': '标记群聊中的指定消息。',
  'removeGroupFavorite': '取消群消息标记，不删除消息。',
  'readGroupAnnouncement': '读取群公告及相关信息。',
  'updateGroupAnnouncement': '更新群公告，需要相应群管理权限。',
  'createGroupChat': '创建群聊并加入明确指定的成员。',
  'renameGroupChat': '修改群聊名称。',
  'updateGroupChatMembers': '添加或移除群成员，遵守成员管理权限。',
  'listAiContacts': '查询 AI 联系人列表。',
  'readAiContact': '读取指定 AI 联系人的资料。',
  'createAiContact': '创建新的 AI 联系人及其身份配置。',
  'updateAiContact': '修改指定 AI 联系人资料和设置。',
  'deleteAiContact': '归档指定 AI 联系人。',
  'restoreAiContact': '恢复已归档的 AI 联系人。',
  'readAttachment': '读取用户提供的附件内容，用于文档、音频或视频等资料分析。',
  'searchImages': '搜索公开参考图片并取得图片及来源链接，不生成新图片。',
  'generateImage': '根据描述生成图片，或按要求修改已有参考图片。',
  'generateMusic': '根据描述生成音乐或歌曲。',
  'searchWeb': '搜索互联网获取相关页面和最新资料。',
  'setSourceDates': '为已取得的来源补充有依据的发布时间或事件时间。',
  'inspectLocalDatabase': '查看允许访问的本地数据库结构，不修改数据。',
  'queryLocalDatabase': '按查询读取允许访问的本地记录，用于实际数据核查。',
  'readLocalDatabase': '读取允许访问的本地数据库记录。',
  'clickUiElement': '点击当前界面中已观察到的元素。',
  'inputUiText': '向当前界面中的输入控件填写文字。',
  'scrollUiForward': '向前滚动当前可滚动区域。',
  'scrollUiBackward': '向后滚动当前可滚动区域。',
  'goBack': '执行设备返回操作。',
  'goHome': '返回设备主屏幕。',
  'readWebPage': '打开并读取指定网页的内容。',
  'listMemories': '搜索或分页读取自己的记忆片段，可按当前项目优先排序。',
  'readMemory': '读取指定记忆及来源线索，用于回忆和核实。',
  'createMemory': '保存用户明确要求记住的独立事实、偏好或经验，保留来源。',
  'updateMemory': '依据明确纠正或新证据修改已有记忆。',
  'deleteMemory': '按用户明确要求删除指定记忆。',
  'prepareMemoryChanges': '准备批量记忆整理建议，供核对后应用。',
  'applyMemoryChanges': '应用已准备并获准的记忆调整。',
  'readRequestAdapters': '读取模型请求转换脚本和配置。',
  'previewRequestAdapter': '试运行请求转换，查看转换结果而不保存设置。',
  'saveRequestAdapter': '保存模型请求转换脚本及启用配置。',
  'readDefaultModels': '读取文字、图像等用途的默认模型设置。',
  'updateDefaultModel': '修改指定用途的默认模型。',
  'getModelBalance': '查询模型供应商账户余额。',
  'openModelTopUp': '打开供应商官方充值页面，支付由用户完成。',
  'searchConversations': '搜索历史会话和任务，取得可继续或读取的原始位置。',
  'searchMessages': '搜索可访问的历史消息内容。',
  'getNetworkState': '读取当前设备网络连接状态。',
  'getNetworkEvents': '读取近期网络状态变化记录。',
  'dnsLookup': '解析指定域名，诊断 DNS 问题。',
  'tlsProbe': '检查目标服务 TLS 握手和证书情况。',
  'httpProbe': '检查指定 HTTPS 地址的请求结果。',
  'getNotifications': '读取已授权的设备通知观察结果。',
  'sendNotification': '向用户发送设备通知。',
  'manageSkill': '管理已有技能的设置和使用状态。',
  'listSkills': '列出当前可用技能。',
  'readSkill': '读取技能完整说明，按其适用范围与权限要求执行。',
  'createSkill': '创建可复用技能及其说明。',
  'updateSkill': '修改已有技能内容。',
  'deleteSkill': '删除指定技能。',
  'installSkill': '安装指定来源的技能。',
  'uninstallSkill': '卸载已安装技能。',
  'enableSkill': '启用指定技能。',
  'disableSkill': '停用指定技能，不删除技能内容。',
  'searchSkills': '搜索技能库中适合当前工作的技能。',
  'runSkill': '执行已读取且适用的脚本技能，遵守其确认要求。',
  'scheduledTask': '管理需要在指定时间或周期执行的定时任务。',
  'createScheduledTask': '创建单次或重复执行的定时任务。',
  'updateScheduledTask': '修改已有定时任务的内容或调度设置。',
  'listScheduledTasks': '查询定时任务及其状态。',
  'pauseScheduledTask': '暂停指定定时任务的后续调度。',
  'resumeScheduledTask': '恢复已暂停的定时任务。',
  'deleteScheduledTask': '删除指定定时任务及其调度。',
  'inspectAndroidApi': '查询当前设备可调用的 Android 接口及参数。',
  'executeAndroidScript': '执行设备脚本完成已授权操作。',
  'observeDevice': '读取当前设备界面的实际状态与元素。',
  'captureScreen': '获取当前屏幕图像用于视觉检查。',
  'tapScreen': '点击当前屏幕中的已确认坐标。',
  'wait': '等待指定时长或状态变化。',
  'waitForUi': '等待界面出现指定变化后继续操作。',
  'askUser': '向用户提出需要补充的信息或选择，可等待真实回答；超时或跳过不代表同意。',
  'requestAccessibilityAccess': '请求用户授权界面观察与操作能力。',
  'act': '根据已观察的当前界面执行明确的设备操作。',
  'findApps': '查找设备上已安装的应用。',
  'launchApp': '启动已确认的设备应用。',
  'startIntent': '启动明确指定的 Android Intent 操作。',
  'openSettings': '打开设备系统设置页面。',
  'getDeviceExtensions': '查询设备提供的扩展能力。',
  'requestShizukuAccess': '请求用户授予 Shizuku 访问权限。',
  'executeShizuku': '通过已授权的 Shizuku 执行命令。',
  'startNetworkCapture': '开始记录设备网络连接用于排障。',
  'stopNetworkCapture': '停止当前网络连接记录。',
  'readNetworkTraffic': '读取已采集的网络连接记录。',
  'clearNetworkTraffic': '清除已采集的网络连接记录。',
  'getDocumentFolders': '列出已授权访问的文件夹。',
  'requestDocumentFolder': '打开文件夹选择器，请用户授权目标目录。',
  'listFiles': '列出指定可访问文件夹中的文件。',
  'searchFiles': '在可访问目录中查找文件。',
  'listProjectTree': '读取当前项目目录结构。',
  'searchProjectText': '在项目文件正文中搜索关键词或代码。',
  'readDocument': '读取指定文档或文件内容。',
  'writeTextFile': '写入指定文本文件内容。',
  'replaceText': '在指定文件中替换明确匹配的文本。',
  'applyTextPatch': '按补丁精确修改文件内容。',
  'createFolder': '在可写目录中创建文件夹。',
  'renameDocument': '重命名指定文件或文档。',
  'copyDocument': '复制文件到指定可写位置。',
  'moveDocument': '移动文件到指定位置。',
  'deleteDocument': '删除指定文件或文档，遵守破坏性操作确认要求。',
  'listProjects': '列出已有项目及其工作目录。',
  'createProject': '创建项目并关联明确的工作目录。',
  'renameProject': '修改项目显示名称。',
  'setProjectIcon': '修改项目图标。',
  'setProjectPinned': '设置或取消项目置顶。',
  'setCurrentConversationProject': '设置当前会话或任务所属项目。',
  'runProjectCommand': '在指定项目工作目录执行已授权命令。',
  'getProjectGitStatus': '读取项目 Git 工作区与分支状态。',
  'getProjectGitDiff': '读取项目 Git 文件差异。',
  'initializeProjectGit': '在指定项目初始化 Git 仓库。',
  'setProjectGitRemote': '设置项目 Git 远端地址。',
  'commitProjectGit': '提交指定项目的 Git 改动。',
  'pullProjectGit': '从项目 Git 远端拉取更新。',
  'pushProjectGit': '将项目 Git 分支推送到远端。',
  'mergeProjectBranch': '合并指定项目的 Git 分支。',
  'checkoutProjectBranch': '切换指定项目的 Git 分支。',
  'readGitConfiguration': '读取 Git 用户身份与相关配置。',
  'updateGitConfiguration': '修改 Git 用户身份与相关配置。',
  'createTextFile': '创建文本文件并保存内容。',
  'deliverFile': '将已生成的文件作为附件交付给用户。',
  'shareFile': '通过设备分享流程分享已有文件。',
  'shell': '在本机工作环境执行命令，用于检查、创建或修改文件和运行程序。',
};
