"""Generate the system-font emoji catalog from pinned Unicode/CLDR releases."""
import json
import pathlib
import re
import urllib.request
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[1]
VERSION = '17.0'
CLDR = 'release-48'

def download(url):
    return urllib.request.urlopen(url).read().decode('utf-8')

def normalize(text):
    return text.replace('\ufe0f', '')

annotations = {}
for folder in ['annotations', 'annotationsDerived']:
    xml = download(f'https://raw.githubusercontent.com/unicode-org/cldr/{CLDR}/common/{folder}/zh.xml')
    for item in ET.fromstring(xml).iter('annotation'):
        entry = annotations.setdefault(normalize(item.attrib['cp']), {})
        entry[item.attrib.get('type', 'keywords')] = item.text

groups = []
rows = []
source = download(f'https://www.unicode.org/Public/{VERSION}.0/emoji/emoji-test.txt')
for line in source.splitlines():
    if line.startswith('# group: '):
        group = line.removeprefix('# group: ')
        if group != 'Component': groups.append(group)
    match = re.match(r'^([0-9A-F ]+)\s*; fully-qualified\s*# (\S+) E[\d.]+ (.+)$', line)
    if not match: continue
    emoji, english = match.group(2, 3)
    annotation = annotations[normalize(emoji)]
    rows.append([emoji, annotation['tts'], english + ' ' + annotation.get('keywords', ''), groups.index(group), emoji])

# Skin-tone sequences share a base entry; gender/family sequences stay discoverable.
by_emoji = {normalize(row[0]): row for row in rows}
for row in rows:
    base = normalize(''.join(c for c in row[0] if not 0x1F3FB <= ord(c) <= 0x1F3FF))
    if base == '\U0001faf1\u200d\U0001faf2': base = '\U0001f91d'
    if base in by_emoji: row[4] = by_emoji[base][0]

asset = ROOT / 'assets/emoji'
asset.mkdir(parents=True, exist_ok=True)
(asset/'catalog.json').write_text(json.dumps({'version':VERSION,'groups':groups,'entries':rows},ensure_ascii=False,separators=(',',':')),encoding='utf-8')
(asset/'LICENSE.txt').write_text(download('https://www.unicode.org/license.txt'),encoding='utf-8')
sequences = [row[0] for row in rows]
lines = ['// Generated by tool/generate_emoji_catalog.py. Unicode 17.0; see assets/emoji/LICENSE.txt.', 'const unicodeEmojiSequences =']
for start in range(0,len(sequences),12):
    lines.append("    '" + ' '.join(sequences[start:start+12]) + (" ';" if start+12>=len(sequences) else " '") )
(ROOT/'lib/src/domain/unicode_emoji_sequences.dart').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps({'entries':len(rows),'baseEntries':sum(r[0]==r[4] for r in rows),'assetBytes':(asset/'catalog.json').stat().st_size}))
