const stages=[
{title:'车上营业',place:'行驶中 · 下一站松岭',intro:'列车已经能用。七名乘客的午餐需求送来了，大家先商量做什么。',actions:['查看三张订单的口味、预算和实际库存。','自由分工做饭、服务、聊天或处理小问题；普通操作直接完成。','缺食材时提出采购、交换或其他办法，DM 确认条件后实际行动。'],result:'餐食交付就收款、扣实际食材，不用等抵站才结算。',links:[[1,'首批订单','第一批三张订单'],[6,'食材与价格',''],[0,'行动与掷骰','场景中的回合与掷骰']]},
{title:'松岭接客',place:'松岭站 · 第一批新客',intro:'风雪突然出现。站内有供暖，约 10—20 名旅客想买票去港湾。',actions:['先确认想上车的人数、同行组、行李和休息需求，再决定接多少人。','松岭至港湾每人 15 元；餐食另点，不把全车人数自动变成订单。','按已谈好的菜单补货，用本站票款支付下一段 60 元牵引燃料。'],result:'乘客安排妥当、补给完成，并由站方确认下一段通行后继续行驶。',links:[[1,'停站怎么处理',''],[6,'本站采购参考',''],[5,'空间与服务','整列车怎样判断接待情况']]},
{title:'途中服务',place:'松岭 → 溪桥',intro:'车上人多了，热饭、行李和窗边漏风都有人需要处理。',actions:['各组同时做事，DM 每次处理一个短场景，再切到其他组。','完成已经接下的订单，按实际库存出餐；车上小卖部取货不额外花钱。','窗缝可以用维修箱材料修好，也可以先把乘客调到暖区。'],result:'记住已经修好的位置、交付的订单和当前空间用途，后续沿用结果。',links:[[1,'厨房经营',''],[4,'道具怎么用',''],[3,'职业效果','']]},
{title:'溪桥安排',place:'溪桥站 · 接客与补给',intro:'约 20—30 名旅客在有供暖的室内候车。先处理原有乘客下车，再看空间。',actions:['空间够就正常安排；不够时，用餐间临时住人花 60 元，暂停堂食但仍可送餐。','草原临时方案花 200 元，保留餐厅；组件要找到、购买并实际安装。','新客到港湾每人 10 元。停站时谈新菜单、采购，并支付下一段 60 元燃料。'],result:'只给实际能安排的旅客售票；未接上的人可继续在暖和的站内等待。',links:[[5,'腾空间的影响','空间决定哪些生意还能做'],[6,'采购参考',''],[1,'设施投入','票款、运行支出与设施投入的比例']]},
{title:'港湾前服务',place:'溪桥 → 港湾',intro:'继续照顾已经上车的人，把答应的饭菜和休息服务落实。',actions:['按同行组或同类餐一起准备和交付，不为每位乘客重复操作。','饮食禁忌按点餐时约定执行，可以分开菜单与标记餐食。','处理仍有影响的问题；已离站就不能继续从那一站买货。'],result:'做完就更新订单、食材与现场；不用完成全部可选生意才能抵达港湾。',links:[[1,'供餐与交付',''],[3,'技能速查',''],[4,'道具速查','']]},
{title:'港湾收尾',place:'港湾站 · 旅程继续',intro:'乘客到站下车，取回行李。风雪事件收束，列车继续经营。',actions:['核对未交付的订单、改程安排和需要归还的乘客物品。','记录真实票款、餐费、采购、燃料与设施支出；补货只有实际购买才扣钱。','买来的用品留下。选择恢复餐厅、继续补货、攒钱或购买翻新设备。'],result:'烤炉含安装 400 元，局部永久卧铺翻新 800 元。团队决定投入时机，再进入下一段旅程。',links:[[1,'设备与经营账','票款、运行支出与设施投入的比例'],[5,'翻新与空间','空间决定哪些生意还能做'],[0,'持续游玩','开始与持续游玩']]}
];
function header(subtitle){return `<header class="top"><div class="eyebrow">ANIMALINE</div><h1 class="title">安宁列车</h1><p class="sub">${subtitle}</p></header>`}
function docButton(index,label,heading=''){return `<button class="secondary" data-doc="${index}" data-section="${heading}">${label}</button>`}
function roleButtons(){return `<div class="role" aria-label="资料模式"><button class="secondary" data-role="player" aria-pressed="${role==='player'}">玩家指南</button><button class="secondary" data-role="dm" aria-pressed="${role==='dm'}">主持人资料</button></div>`}
function guide(){
const current=stages[stage];
app.innerHTML=header('动物列车 · 经营、自由发挥与沿途事件')+`
<section class="card hero"><h2>一起经营这趟无尽旅程</h2><p>旧绿皮列车已投入运营。接客、做饭、处理小麻烦，把赚来的钱用于补货和翻新。</p><p class="small">旅途指南与规则速查。点击阶段查看怎么开展；售票、库存和小游戏仍由桌上主持与操作完成。</p></section>
${roleButtons()}
<section class="card"><h2>这趟怎么走</h2><p class="small">可以分头做事，不必做完所有额外生意。下方按钮用于查看阶段。</p><nav class="route" aria-label="旅途阶段">${stages.map((item,index)=>`<button class="secondary" data-stage="${index}" aria-pressed="${stage===index}">${item.title}</button>`).join('')}</nav><div class="stage"><div class="eyebrow">${current.place}</div><h3>${current.title}</h3><p>${current.intro}</p><ul class="rules">${current.actions.map(action=>`<li>${action}</li>`).join('')}</ul><p class="notice">${current.result}</p><div class="buttons">${current.links.map(([index,label,heading])=>docButton(index,label,heading)).join('')}</div>${role==='dm'?`<div class="buttons">${docButton(7,'本阶段主持参考', ['玩家开始时知道什么','松岭：上车前先把生意说清楚','松岭至溪桥：让已经上车的人住得下、吃得上','溪桥：接新客之前决定列车怎样营业','溪桥至港湾：采购决定能卖什么','港湾：把本次经营收好，留下新的设施'][stage])}</div>`:''}<div class="stageFooter">${stage>0?`<button class="ghost" data-stage="${stage-1}">查看上一阶段</button>`:'<span></span>'}${stage<5?`<button class="secondary" data-stage="${stage+1}">查看下一阶段</button>`:'<button class="secondary" data-stage="0">回看日常营业</button>'}</div></div></section>
<section class="card"><div class="characterEntry"><img src="${animals[selectedAnimal].art.src}" alt="${animals[selectedAnimal].name}" width="80" height="80"><div><h2>动物 × 职业</h2><p class="small">八种动物、六种职业自由组合。先看看你的两项本领。</p></div></div><div class="buttons"><button class="secondary" data-view="characters">查看角色卡片</button></div></section>
<section class="card"><h2>随手查规则</h2><div class="quick">${[[2,'动物技能','物种本领'],[3,'职业技能','专业效果'],[4,'背包与道具','占位、次数与转交'],[6,'食材与种子','品种、采购价与来源'],[5,'车厢与服务','空间、营业与布置'],[1,'经营与投入','订单、成本与翻新']].map(([index,title,detail])=>`<button class="action" data-doc="${index}"><b>${title}</b><span>${detail}</span></button>`).join('')}</div><div class="buttons"><button class="ghost" data-view="list">全部规则资料</button></div></section>
${role==='dm'?`<section class="card"><h2>风雪事件主持资料</h2><p class="small">包含幕后事实、现场任务和结算示例。玩家指南不展开这些内容。</p><div class="buttons">${docButton(7,'八个现场场景','可以直接主持的沿途场景')}${docButton(7,'幕后事实','主持人提前确定的事实')}${docButton(7,'两种方案的账','一趟经营的对照账')}</div></section>`:''}`;
}
