function home(){
const state=typeof AuraiHTML==='undefined'?null:AuraiHTML.messageState,host=state?state._miniapp:null;
const running=host&&state.phase!=='setup';
app.innerHTML=header(running?'旅程状态 · 在群聊中继续行动':'群聊跑团 · 列车后台')+`<section class="card hero"><h2>${running?escape(state.scene.title):'在群聊里，一起经营安宁列车'}</h2><p>${running?escape(state.scene.description):'玩家在群里讨论、分工和自由行动，DM 描述现场并调用后台记录结果。这里查看角色、订单、库存与列车状况。'}</p>${running?`<p class="small">${escape(state.scene.mode)} · ${escape(state.scene.mode==='停站'?state.scene.station:'前往'+state.scene.nextStation)} · ${escape(state.scene.crowding)}</p>`:'<p class="small">把小程序发送到群聊，选择主持 AI 和玩家即可开始。无需通过页面点击阶段推进。</p>'}</section>`;
if(host&&!running){
const canStart=host.viewerId===host.ownerId||host.viewerId==='user:local';
app.innerHTML+=`<section class="card"><h2>开始旅程</h2>${canStart?`<form id="journeySetup"><label class="fieldLabel" for="journeyHost">主持 AI</label><select id="journeyHost" class="professionSelect" required><option value="">选择主持人</option>${host.members.filter(m=>m.kind==='agent').map(m=>`<option value="${escape(m.id)}">${escape(m.name)}</option>`).join('')}</select><h3>参与玩家与角色</h3><p class="small">可选择相同动物和职业。主持 AI 不兼任玩家。</p>${host.members.map(m=>`<div class="setupPlayer" data-member="${escape(m.id)}"><label><input type="checkbox" name="player" value="${escape(m.id)}"> ${escape(m.name)}</label><div class="setupChoices"><select aria-label="${escape(m.name)}的动物">${animals.map(a=>`<option>${a.name}</option>`).join('')}</select><select aria-label="${escape(m.name)}的职业">${professions.map(p=>`<option>${p.name}</option>`).join('')}</select></div></div>`).join('')}<div class="buttons"><button class="primary" type="submit">开始群聊旅程</button></div></form>`:'<p class="small">由发送此小程序的成员配置主持人与玩家。</p>'}</section>`;
}else if(running){
app.innerHTML+=`<section class="card"><h2>列车概况</h2><div class="quick"><div class="skillPanel"><span class="skillKind">共有资金</span><h3>${state.cash} 元</h3></div><div class="skillPanel"><span class="skillKind">在车乘客</span><h3>${state.passengers.filter(p=>p.onboard).reduce((n,p)=>n+p.count,0)} 位</h3></div></div><p class="small">${state.phase==='paused'?'旅程已暂停，等待主持人在群聊恢复。':'在群聊描述你的行动，由 DM 按实际结果结算。'}</p></section><section class="card"><h2>团队角色</h2><div class="characterGrid">${state.players.map(p=>{const a=animals.find(a=>a.name===p.animal),profession=professions.find(v=>v.name===p.profession);return `<div class="characterPick"><div class="characterArt"><img loading="lazy" decoding="async" src="${a.art.src}" alt="${p.animal}"></div><div class="characterBody"><strong>${escape(p.name)}</strong><span>${p.animal} · ${p.profession}</span><span class="skillName">${a.skill} · ${profession.skill}</span><span class="skillEffect">${escape(a.effect)}<br>${escape(profession.effect)}</span></div></div>`}).join('')}</div></section><section class="card"><h2>待交付订单</h2>${state.orders.length?'':'<p class="small">当前没有待交付订单。</p>'}${state.orders.map(o=>`<div class="skillPanel"><strong>${escape(o.title)} · ${o.servings} 份</strong><p>${escape(o.requirements)}</p><p class="small">${escape(o.status)} · 约定 ${o.price} 元</p></div>`).join('')}</section><section class="card"><details><summary>共享库存与本站供应</summary><div class="tableWrap"><table><tr><th>物资</th><th>剩余</th></tr>${Object.entries(state.inventory).filter(([,q])=>q>0).map(([name,q])=>`<tr><td>${escape(name)}</td><td>${q}</td></tr>`).join('')}</table></div>${state.offers.length?`<p class="small">本站供应：${state.offers.map(o=>escape(o.name)+' '+o.quantity+'份 / '+o.price+'元').join('；')}</p>`:''}</details></section><section class="card"><details><summary>乘客与设施</summary>${state.passengers.filter(p=>p.onboard).map(p=>`<p><strong>${escape(p.name)}</strong> · ${p.count} 位 → ${escape(p.destination)}</p><p class="small">${escape(p.requirements)}</p>`).join('')}${state.facilities.map(f=>`<p>${escape(f.name)} · ${escape(f.status)}<br><span class="small">${escape(f.use)}</span></p>`).join('')}</details></section>${state.event.title?`<section class="card"><h2>${escape(state.event.title)}</h2><p>${escape(state.event.progress)}</p><ul>${state.event.known.map(v=>`<li>${escape(v)}</li>`).join('')}</ul></section>`:''}<section class="card"><details><summary>最近账本与行动记录</summary>${state.ledger.slice().reverse().map(row=>`<p>${escape(row.note)}${row.cash?' · '+(row.cash>0?'+':'')+row.cash+' 元':''}<br><span class="small">余额 ${row.balance} 元</span></p>`).join('')||'<p class="small">旅程刚开始，还没有经营记录。</p>'}</details></section>`;
if(state.preparedFood.length)app.innerHTML+=`<section class="card"><h2>已记录的额外餐食</h2>${state.preparedFood.map(food=>`<p><strong>${escape(food.menu)}</strong> · ${food.servings} 份</p>`).join('')}</section>`;
if(state.archiveCounts.orders>0)app.innerHTML+=archivePanel('archive-orders','历史订单');
if(state.archiveCounts.passengers>0)app.innerHTML+=archivePanel('archive-passengers','已下车乘客');
if(state.archiveCounts.ledger>10)app.innerHTML+=archivePanel('archive-ledger','较早账本与行动记录',10);
}
app.innerHTML+=`<section class="card"><h2>规则资料</h2><div class="buttons"><button class="secondary" data-view="characters">角色与技能参考</button><button class="secondary" data-view="guide">旅途指南</button><button class="secondary" data-view="list">全部资料</button></div></section>`;
if(host&&!running){const form=document.getElementById('journeySetup');if(form){const hostSelect=document.getElementById('journeyHost');hostSelect.onchange=()=>{form.querySelectorAll('[data-member]').forEach(row=>{const chosen=row.dataset.member===hostSelect.value;row.hidden=chosen;if(chosen)row.querySelector('input').checked=false})};form.onsubmit=event=>{event.preventDefault();void configureJourney(form).catch(showPageError)};}}
}

async function configureJourney(form){const players=[...form.querySelectorAll('[data-member]')].filter(row=>row.querySelector('input').checked).map(row=>({memberId:row.dataset.member,animal:row.querySelectorAll('select')[0].value,profession:row.querySelectorAll('select')[1].value}));const button=form.querySelector('button[type=submit]');button.disabled=true;try{await AuraiHTML.submitEvent({eventId:crypto.randomUUID(),action:'configure',data:{hostId:hostSelect.value,players},notifyAi:false});home()}finally{button.disabled=false}}
