var protocol='你是安宁列车 DM，负责现场叙事与自由行动裁定，程序负责记账。已有当前运行时快照或上次事件返回状态/版本时直接使用；缺状态或版本冲突再 readHtmlProgram，不重复读取。同一短场景里已经确认并执行的经营操作用 batch 一次提交（1–12项，原子结算），不要把尚待玩家决定的操作提前执行。事件重试沿用 eventId，失败报告真实原因，不轮询。普通行动直接成功，有风险才掷骰，不逐分钟推进、不为每位乘客逐个结算。按需 readHtmlProgram(resourceKey) 查 references：文档键返回章节目录，再选需要的章节；archive 键分页读取旧订单、乘客、账本。禁止为查规则读取整个 HTML 或全部历史。离站、暂停、事件收尾前把未完约定、线索、人物关系和进行中的行动保存为 journal，depart/pause/checkpoint 会切换上下文。journal仅保存玩家已知且仍有效的事实，已结事项不反复抄写；未公开事实保存于setEvent.secrets，不能写进公开journal。幕后事实不公开；先确认菜单、价格和限制，实际行动后记账。未自动化的技能、道具、掷骰与种植按规则裁定，以 resolve 记结果；不宣称已自动计算。';
var actions={configure:'{hostId,players:[{memberId,animal,profession}]} 创建人开局',setCharacter:'{memberId,animal,profession} 营业前绑定角色',arrive:'{station,nextStation}',depart:'{lineConfirmed:true,journal:{commitments:[未完约定],clues:[有效线索],relationships:[人物关系],ongoing:[进行中行动]}} 保存笔记后离站并切换上下文',setOffers:'{offers:[{name,quantity,price}]} 本站真实有限货物',purchase:'{items:[{name,quantity}],note,memberId?} 商人折扣',supply:'{cost,note,memberId?} 下一路段燃料，只付一次',acquire:'{items:[{name,quantity}],note,executed:true} 实际取得免费物资',board:'{id,name,count,destination,requirements,fare,arrangementConfirmed:true}',alight:'{groupId}',reroute:'{groupId,destination,extraFare,agreed:true}',addOrder:'{id,groupId,title,requirements,servings,price}',deliver:'{orderId,ingredients:[{name,quantity}],baseServings,menu,agreed:true,memberId?} 厨师倍率按同款一批；只交付一单，额外份数保留在订单记录，不自动卖给别人',cancelOrder:'{orderId,note,agreed:true}',install:'{name,use,items:[{name,quantity}]} 消耗已买到的设备或配套用品',repair:'{name,status,materials:[{name,quantity}],indivisible:[name],memberId?,note}',setScene:'{title,description,crowding:宽松|忙碌|拥挤} 不改车站位置',setEvent:'{title,progress,known:[公开事实],secrets:[幕后事实]}',resolve:'{note} 记录实际裁定，不变更钱物',refund:'{amount,note}',pause:'{journal:{commitments:[],clues:[],relationships:[],ongoing:[]}} 保存笔记后暂停',resume:'{}'};
actions.batch='{operations:[{action,data}]} 1–12 个已落实的经营操作；按顺序原子结算，任何失败整批不提交；depart/checkpoint仅一次且置于末尾';
actions.checkpoint='{journal:{commitments:[],clues:[],relationships:[],ongoing:[]}} 事件收尾保存仍有效事实并切换上下文';
actions.amendOrder='{orderId,title,requirements,servings,price,agreed:true} 修改待交付订单，如松茸版面条';
actions.setFacility='{name,status,use,note} 已落实的临时用途和故障状态';
var view=s.phase==='setup'?{phase:'setup'}:{phase:s.phase,hostId:s.hostId,players:s.players,cash:s.cash,inventory:Object.fromEntries(Object.entries(s.inventory).filter(function(row){return row[1]>0;})),passengers:s.passengers.filter(function(p){return p.onboard;}),orders:s.orders.filter(function(o){return o.status==='待交付';}),preparedFood:s.orders.filter(function(o){return o.extraServings>0;}).map(function(o){return {orderId:o.id,title:o.title,menu:o.menu,servings:o.extraServings};}),facilities:s.facilities,scene:s.scene,event:s.event,offers:s.offers,routePaid:s.routePaid,ledger:s.ledger.slice(-10),journal:s.journal,archiveCounts:{orders:s.orders.filter(function(o){return o.status!=='待交付';}).length,passengers:s.passengers.filter(function(p){return !p.onboard;}).length,ledger:s.ledger.length}};
if(s.phase!=='setup'){
 s.players.forEach(function(p){p.name=member(p.memberId).name;privateViews[p.memberId]={character:p,skills:{animal:rules.animals.filter(function(a){return a.name===p.animal;})[0],profession:rules.professions.filter(function(a){return a.name===p.profession;})[0]},references:referenceIndex.filter(function(r){return /^doc-[0-6]$/.test(r.key);}),protocol:'在群聊讨论并描述行动，DM审核后由后台结算；页面查看状态。按需 readHtmlProgram(resourceKey) 查规则，文档键先返回章节目录，不读取完整HTML。'};});
 var currentActions={batch:actions.batch,resolve:actions.resolve,setScene:actions.setScene,setEvent:actions.setEvent,setFacility:actions.setFacility,checkpoint:actions.checkpoint,pause:actions.pause,acquire:actions.acquire,deliver:actions.deliver,addOrder:actions.addOrder,amendOrder:actions.amendOrder,cancelOrder:actions.cancelOrder,repair:actions.repair,refund:actions.refund};
 (s.scene.mode==='停站'?['depart','setOffers','purchase','supply','board','alight','reroute','install']:['arrive']).forEach(function(key){currentActions[key]=actions[key];});
 if(s.phase==='paused')currentActions={resume:actions.resume};
 if(!s.ledger.some(function(row){return row.kind!=='角色';}))currentActions.setCharacter=actions.setCharacter;
 var hostView={isHost:true,canEditData:true,canSubmitForPlayers:true,secrets:s.secrets,actions:currentActions,references:referenceIndex,protocol:protocol};
 privateViews[s.hostId]=hostView;
 if(ctx.ownerId!==s.hostId)privateViews[ctx.ownerId]=hostView;
}
return {state:s,view:view,privateViews:privateViews};
