const miniappProgramGuide =
    'For program-controlled shared workflows, include '
    '<script type="application/json" id="aurai-send-action">{"type":"program"}</script> '
    'and a host-only <script type="application/aurai-program"> reducer body </script>. '
    'The reducer runs without a WebView, DOM, network, Java or database access. '
    'It receives ctx={state,event:{actorId,action,data},members:[{id,name,kind}],ownerId,messageId,now}. '
    'ownerId is the authenticated sender of this message instance, whether human or AI; it is not the app template author or always the local user. The sender may configure their own instance and choose its host without requiring a human to operate the page. '
    'Initial private state is {}; initial public view is {phase:"setup"}. '
    'Declare only needed host operations in <script type="application/json" id="aurai-capabilities">["messages.send","cards.close"]</script>. '
    'Available operation names: messages.send, messages.intercept, cards.close, cards.submit, replies.set, replies.release, members.rename, timer.set. '
    'The reducer receives an injected frozen host with host.call(name,args). Undeclared operations are rejected by both runtime and host; declarations never bypass actor permissions. '
    'Calls enqueue effects, do not return results or perform immediate I/O. Return only {state,view,privateViews}; old effect fields are rejected. '
    'At most 128 calls and 64 messages per event. Repeated messages.send/cards.close calls are allowed; other operations may be called once. '
    'Effects commit with state in host order: nicknames, reply control, card submission, card closure, messages, then state/timer. Call order does not change this order. '
    'Example: host.call("messages.send",{text:"Ready"}); return {state:ctx.state,view:{phase:"ready"},privateViews:{}}. '
    'state is host-only (max 256 KB); view is public; privateViews maps authenticated member IDs to their permitted data. '
    'Never place identities, secret actions or private results in view, HTML or shared values. '
    'The page reads AuraiHTML.messageState and its _miniapp={viewerId,ownerId,members,own,cards}; '
    'the host strips the reducer before rendering and does not save shared image previews for these messages. '
    'host.call("messages.intercept",{actors:[aiMemberIds],action:eventName}) takes over ordinary AI group message publication for those members in this instance. Every reducer output replaces the interception list; omit it or use actors:[] to release. The host invokes this event with authenticated actorId and data:{text,markdown} BEFORE publishing. Your reducer must validate phase and permission, then emit exactly one message with senderId equal to that actor; choose audience programmatically. Failures publish nothing. The original sendGroupMessage audience is not used. Images, attachments and quotes are rejected while intercepted. Explicit program/channel events remain available. Multiple instances claiming the same actor fail rather than guess. This is separate from replies.set: pausing AI never changes message visibility. '
    'host.call("messages.send", args) sends messages; args are {text,markdown?,audience?,wakeAi?,wakeMemberIds?,senderId?}; optional wakeMemberIds limits waking to those AI recipients within audience without narrowing who can read. senderId may only equal the authenticated event.actorId and attributes the message to that actor; omit it for program system messages. Omit audience for public messages, '
    'and provide an explicit audience when waking AI. Optional {card,key,event,data} creates a native action or shared vote card '
    'with the usual buttons/interaction definition and explicit audience. For shared voting, use one card with interaction.actors, completion, reveal and views; participation configures choices/summary visibility (private by default). actorWeights supports weighted ballots. senderId attributes it to the authenticated host, wakeMemberIds targets eligible voters only. Submissions update the shared card and run your reducer atomically '
    'with authenticated actor and event.data={context:the declared data,value:the submitted choice}; '
    'For referee proxy submissions, expose canSubmitForPlayers:true only in authorized referee/creator private views. '
    'The referee sends the normal player action with data.submitForPlayerId plus its original context/value. '
    'The reducer must authorize the real ctx.event.actorId, validate the target player, phase and choice, and call '
    'host.call("cards.submit",{key:the active declared card key,actorId:targetPlayerId,value:the original option value}). '
    'At most one card may be submitted per event. Native selections, player participant records, weighted votes and '
    'the program event commit atomically; the event keeps the real submitter identity. Emit before closing that card. '
    'host.call("cards.close",{keys:[...]}) closes active cards by your declared keys, preserving shared choices and results. Do not put notifyAi or callbackEvents on program-owned cards; your reducer controls further AI wakes. '
    'host.call("replies.set",{states:{memberId:enabled}}) maps current AI member IDs to enabled booleans. false stops their current run and blocks all wakes, including mentions and program events. To start an AI, set its replies.set entry to true and send an audience-targeted wakeAi:true message in the same output. wakeAi does not enable a disabled AI. Disable each actor after their action completes. host.call("replies.release",{}) restores their original states; do not combine with replies.set in one event. '
    'host.call("members.rename",{names:{memberId:nickname}}) maps current group member IDs to group nicknames (max 32 characters), committed atomically with the event without changing global profile names or private remarks. The event actor may change their own nickname; changing others requires the actor to be the group owner or administrator. ctx.members contains current group nicknames in name and original profile names in originalName. '
    'host.call("timer.set",{at:null}) cancels the timer; at:futureEpochMilliseconds schedules action:"timer" as system:timer. Without a call, the existing timer is retained; a fired timer is consumed unless rescheduled. '
    'For explicit instance data maintenance, readHtmlData/updateHtmlData read and replace {state,view,privateViews} atomically with version checking. Authors and members whose private view has canEditData:true can edit directly; others request user approval. Keep all projections consistent, preserve secrets and use normal program events for gameplay. '
    'State, card effects and replies commit atomically. Validate actors, phase and legal choices in the reducer; '
    'event IDs deduplicate retries. Human submitEvent runs the program first; it does not automatically wake an AI. '
    'The program decides which messages/cards wake which AI. AI can read its own projection with readHtmlProgram '
    'and return allowed events with submitHtmlProgramEvent (version checked), or use clickInteractiveMessage '
    'on its assigned native card. To end and resume an AI speech, use an explicit completion card/event, '
    'call replies.set and wake the next permitted speaker. Do not introduce a referee or expose private data '
    'unless the user explicitly wants that role. Program sessions are isolated per launcher; use source updates '
    'for future sessions, never overwrite a running session state with updateHtmlMessage. ';
