const miniappProgramGuide =
    'For program-controlled shared workflows, include '
    '<script type="application/json" id="aurai-send-action">{"type":"program"}</script> '
    'and a host-only <script type="application/aurai-program"> reducer body </script>. '
    'The reducer runs without a WebView, DOM, network, Java or database access, with a 100 ms execution limit. '
    'It receives ctx={state,event:{actorId,action,data},members:[{id,name,kind}],ownerId,messageId,now}. '
    'Initial private state is {}; initial public view is {phase:"setup"}. '
    'Return {state,view,privateViews,messages,closeKeys,replyStates,releaseReplyControl,wakeAt}. '
    'state is host-only (max 256 KB); view is public; privateViews maps authenticated member IDs to their permitted data. '
    'Never place identities, secret actions or private results in view, HTML or shared values. '
    'The page reads AuraiHTML.messageState and its _miniapp={viewerId,ownerId,members,own,cards}; '
    'the host strips the reducer before rendering and does not save shared image previews for these messages. '
    'Messages (max 64 per event) are {text,audience?,wakeAi?}; omit audience for public messages, '
    'and provide an explicit audience when waking AI. Optional {card,key,event,data} creates a private native action card '
    'with the usual buttons/interaction definition and explicit audience. Its submit callback first runs your reducer '
    'with authenticated actor and event.data={context:the declared data,value:the submitted choice}; '
    'closeKeys closes active cards by your declared keys. Do not put notifyAi on program-owned buttons. '
    'replyStates maps current AI member IDs to enabled booleans; releaseReplyControl:true restores their original states. '
    'wakeAt:null disables timers; an absolute future epoch-millisecond deadline calls action:"timer" as system:timer. '
    'State, card effects and replies commit atomically. Validate actors, phase and legal choices in the reducer; '
    'event IDs deduplicate retries. Human submitEvent runs the program first; it does not automatically wake an AI. '
    'The program decides which messages/cards wake which AI. AI can read its own projection with readHtmlProgram '
    'and return allowed events with submitHtmlProgramEvent (version checked), or use clickInteractiveMessage '
    'on its assigned native card. To end and resume an AI speech, use an explicit completion card/event, '
    'update replyStates and wake the next permitted speaker. Do not introduce a referee or expose private data '
    'unless the user explicitly wants that role. Program sessions are isolated per launcher; use source updates '
    'for future sessions, never overwrite a running session state with updateHtmlMessage. ';
