import '../domain/tool_models.dart';
import '../domain/quick_reply_option.dart';

const aiQuickReplyKeys = {
  'dog',
  'like',
  'dislike',
  'love',
  'laugh',
  'celebrate',
  'plus_one',
  'done',
  'received',
  'viewing',
  'question',
  'smile',
  'surprised',
  'sad',
  'angry',
  'thinking',
  'sweat',
  'speechless',
  'cool',
  'clap',
  'thanks',
  'strong',
  'fire',
  'hundred',
  'hug',
  'heart_eyes',
  'rainbow',
  'flower',
  'gift',
  'rocket',
  'coffee',
  'diamond',
  'clover',
  'ice',
  'party',
  'bullseye',
  'penguin',
  'cat',
  'unicorn',
  'ghost',
  'robot',
  'poop',
  'melon',
  'lemon',
  'beer',
  'broken_heart',
  'wilted_flower',
  'sleep',
  'sob',
  'touched',
  'eye_roll',
  'mind_blown',
  'salute',
  'handshake',
  'panda',
  'fox',
  'popcorn',
  'brain',
  'trophy',
  'heart_hands',
  'skull',
  'alien',
  'see_no_evil',
  'shush',
  'zip_mouth',
  'yawn',
  'sick',
  'melting',
  'upside_down',
  'wink',
  'wave',
  'fist_bump',
  'victory',
  'point_up',
  'writing',
  'frog',
  'rabbit',
  'bear',
  'tiger',
  'dragon',
  'butterfly',
  'snail',
  'turtle',
  'shark',
  'pizza',
  'cake',
  'milk_tea',
  'cheers',
  'sparkles',
  'bomb',
  'grin',
  'beaming',
  'rolling_laugh',
  'kiss',
  'pleading',
  'sleepy',
  'good_night',
  'moon',
  'star',
  'wish',
  'good_morning',
  'sun',
  'rose',
  'smiling_hearts',
  'star_struck',
  'peeking',
  'giggle',
  'bee',
  'owl',
  'otter',
  'chick',
  'sparkling_heart',
  'two_hearts',
  'love_letter',
  'strawberry',
  'cherries',
  'chocolate',
  'ice_cream',
  'sunflower',
  'tulip',
  'daisy',
  'maple_leaf',
  'snowflake',
  'proud',
  'scared',
  'nauseated',
  'drooling',
  'sneezing',
  'party_face',
};

final quickReplyTexts = {
  for (final key in aiQuickReplyKeys) key: quickReplyOptionsByKey[key]!.text,
};

class QuickReplyTool implements AgentTool, RuntimeCapabilityAgentTool {
  QuickReplyTool(this.send);
  final Future<Map<String, Object?>> Function(String messageId, String key)
  send;

  @override
  ToolDefinition get definition => ToolDefinition(
    name: 'sendQuickReply',
    capabilityId: 'local.messages',
    safety: ToolSafety.lowRisk,
    description:
        '向当前会话中可见的消息发送快捷消息（快捷回复、表情回应），显示在原消息下方。同一人可发送多种类型，每种类型最多一项；发送新类型会保留已有类型。适合点赞、点踩、喜欢、哈哈、庆祝、附议、完成、收到、在看、疑问，避免为简单回应另发长消息。messageId 从消息上下文获取，不要让用户填写。',
    inputSchema: {
      'type': 'object',
      'properties': {
        'messageId': {'type': 'string'},
        'key': {'type': 'string', 'enum': quickReplyTexts.keys.toList()},
      },
      'required': ['messageId', 'key'],
      'additionalProperties': false,
    },
  );

  @override
  Future<ToolResult> execute(ToolCall call) async {
    try {
      return ToolResult(
        callId: call.id,
        toolName: call.name,
        status: ToolResultStatus.success,
        output: await send(
          call.arguments['messageId'] as String,
          call.arguments['key'] as String,
        ),
      );
    } on Object catch (error) {
      return ToolResult(
        callId: call.id,
        toolName: call.name,
        status: ToolResultStatus.error,
        output: {'message': error.toString()},
      );
    }
  }

  @override
  Future<void> cancel() async {}
}
