import '../domain/tool_models.dart';

const quickReplyTexts = {
  'dog': '🐶 狗头',
  'like': '👍 点赞',
  'dislike': '👎 点踩',
  'love': '❤️ 喜欢',
  'laugh': '😂 哈哈',
  'celebrate': '🎉 庆祝',
  'plus_one': '+1 附议',
  'done': '✅ 完成',
  'received': '👌 收到',
  'viewing': '👀 在看',
  'question': '❓ 有疑问',
  'smile': '😊 开心',
  'surprised': '😮 惊讶',
  'sad': '😢 难过',
  'angry': '😡 生气',
  'thinking': '🤔 思考',
  'sweat': '😅 尴尬',
  'speechless': '😑 无语',
  'cool': '😎 酷',
  'clap': '👏 鼓掌',
  'thanks': '🙏 感谢',
  'strong': '💪 加油',
  'fire': '🔥 火热',
  'hundred': '💯 满分',
  'hug': '🤗 抱抱',
  'heart_eyes': '😍 心动',
  'rainbow': '🌈 彩虹',
  'flower': '🌸 送花',
  'gift': '🎁 礼物',
  'rocket': '🚀 起飞',
  'coffee': '☕ 喝杯咖啡',
  'diamond': '💎 珍贵',
  'clover': '🍀 好运',
  'ice': '🧊 冷静',
  'party': '🎊 欢庆',
  'bullseye': '🎯 说到点上',
  'penguin': '🐧 企鹅',
  'cat': '🐱 猫猫',
  'unicorn': '🦄 独角兽',
  'ghost': '👻 幽灵',
  'robot': '🤖 机器人',
  'poop': '💩 便便',
  'melon': '🍉 吃瓜',
  'lemon': '🍋 酸了',
  'beer': '🍺 干杯',
  'broken_heart': '💔 心碎',
  'wilted_flower': '🥀 枯萎',
  'sleep': '💤 困了',
  'sob': '😭 大哭',
  'touched': '🥹 感动',
  'eye_roll': '🙄 白眼',
  'mind_blown': '🤯 震惊',
  'salute': '🫡 敬礼',
  'handshake': '🤝 握手',
  'panda': '🐼 熊猫',
  'fox': '🦊 狐狸',
  'popcorn': '🍿 看戏',
  'brain': '🧠 聪明',
  'trophy': '🏆 冠军',
  'heart_hands': '🫶 比心',
  'skull': '💀 笑死',
  'alien': '👽 外星人',
  'see_no_evil': '🙈 没眼看',
  'shush': '🤫 嘘',
  'zip_mouth': '🤐 保密',
  'yawn': '🥱 打哈欠',
  'sick': '🤒 不舒服',
  'melting': '🫠 融化',
  'upside_down': '🙃 倒着笑',
  'wink': '😉 眨眼',
  'wave': '👋 挥手',
  'fist_bump': '👊 碰拳',
  'victory': '✌️ 耶',
  'point_up': '☝️ 注意',
  'writing': '✍️ 记下了',
  'frog': '🐸 青蛙',
  'rabbit': '🐰 兔兔',
  'bear': '🐻 小熊',
  'tiger': '🐯 老虎',
  'dragon': '🐉 龙',
  'butterfly': '🦋 蝴蝶',
  'snail': '🐌 慢慢来',
  'turtle': '🐢 不着急',
  'shark': '🦈 鲨鱼',
  'pizza': '🍕 披萨',
  'cake': '🎂 生日快乐',
  'milk_tea': '🧋 奶茶',
  'cheers': '🥂 庆功',
  'sparkles': '✨ 闪亮',
  'bomb': '💣 炸了',
  'grin': '😀 笑脸',
  'beaming': '😁 灿烂',
  'rolling_laugh': '🤣 笑翻',
  'kiss': '😘 亲亲',
  'pleading': '🥺 可怜',
  'sleepy': '😴 睡着',
  'good_night': '🌃 晚安',
  'moon': '🌙 月亮',
  'star': '⭐ 星星',
  'wish': '🌠 许愿',
  'good_morning': '🌅 早安',
  'sun': '☀️ 太阳',
  'rose': '🌹 玫瑰',
  'smiling_hearts': '🥰 幸福',
  'star_struck': '🤩 崇拜',
  'peeking': '🫣 偷看',
  'giggle': '🤭 偷笑',
  'bee': '🐝 蜜蜂',
  'owl': '🦉 猫头鹰',
  'otter': '🦦 水獭',
  'chick': '🐥 小鸡',
  'sparkling_heart': '💖 闪亮的心',
  'two_hearts': '💕 两颗心',
  'love_letter': '💌 情书',
  'strawberry': '🍓 草莓',
  'cherries': '🍒 樱桃',
  'chocolate': '🍫 巧克力',
  'ice_cream': '🍦 冰淇淋',
  'sunflower': '🌻 向日葵',
  'tulip': '🌷 郁金香',
  'daisy': '🌼 雏菊',
  'maple_leaf': '🍁 枫叶',
  'snowflake': '❄️ 雪花',
  'proud': '😤 不服',
  'scared': '😱 惊恐',
  'nauseated': '🤢 恶心',
  'drooling': '🤤 馋了',
  'sneezing': '🤧 感冒',
  'party_face': '🥳 派对',
};

class QuickReplyTool implements AgentTool, RuntimeCapabilityAgentTool {
  QuickReplyTool(this.send);
  final Future<Map<String, Object?>> Function(String messageId, String key)
  send;

  @override
  ToolDefinition get definition => ToolDefinition(
    name: 'sendQuickReply',
    capabilityId: 'local.messages',
    safety: ToolSafety.lowRisk,
    description:
        '向当前会话中可见的消息发送快捷消息（快捷回复、表情回应），显示在原消息下方。同一人可发送多种类型，每种类型最多一项；发送新类型会保留已有类型。适合点赞、点踩、喜欢、哈哈、庆祝、附议、完成、收到、在看、疑问，避免为简单回应另发长消息。messageId 从消息上下文获取，不要让用户填写。',
    inputSchema: {
      'type': 'object',
      'properties': {
        'messageId': {'type': 'string'},
        'key': {'type': 'string', 'enum': quickReplyTexts.keys.toList()},
      },
      'required': ['messageId', 'key'],
      'additionalProperties': false,
    },
  );

  @override
  Future<ToolResult> execute(ToolCall call) async {
    try {
      return ToolResult(
        callId: call.id,
        toolName: call.name,
        status: ToolResultStatus.success,
        output: await send(
          call.arguments['messageId'] as String,
          call.arguments['key'] as String,
        ),
      );
    } on Object catch (error) {
      return ToolResult(
        callId: call.id,
        toolName: call.name,
        status: ToolResultStatus.error,
        output: {'message': error.toString()},
      );
    }
  }

  @override
  Future<void> cancel() async {}
}
