"""Build Animaline from UI, reducer and reference modules, sharing bundled portraits."""
from pathlib import Path
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'miniapps/animaline'


def encoded(value):
    return json.dumps(value, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/')


def build():
    resources = []
    rules = json.loads((SOURCE / 'rules.json').read_text(encoding='utf-8'))
    documents = json.loads((SOURCE / 'documents.json').read_text(encoding='utf-8'))
    for index, document in enumerate(documents):
        body = (ROOT / 'docs' / document['fileName']).read_text(encoding='utf-8')
        chunks = re.split(r'(?=^## )', body, flags=re.M)
        sections = []
        for number, content in enumerate(chunks):
            key = f'doc-{index}-{number}'
            title = content.splitlines()[0].lstrip('# ').strip()
            sections.append({'key': key, 'title': title})
            resources.append({'key': key, 'title': title, 'access': 'host' if index == 7 else 'public', 'content': content})
        document.update(key=f'doc-{index}', sections=sections)
        resources.append({'key': document['key'], 'title': document['title'], 'access': 'host' if index == 7 else 'public', 'sections': sections})
    for field, title in [('orders', '历史订单'), ('passengers', '历史乘客'), ('ledger', '历史账本')]:
        resource = {'key': 'archive-' + field, 'title': title, 'access': 'public', 'stateField': field}
        if field == 'orders':
            resource['exclude'] = {'field': 'status', 'value': '待交付'}
        if field == 'passengers':
            resource['exclude'] = {'field': 'onboard', 'value': True}
        resources.append(resource)
    portraits = json.loads((SOURCE / 'portraits.json').read_text(encoding='utf-8'))
    for portrait in portraits['avatars']:
        asset = ROOT / 'assets' / portrait['asset']
        if not asset.is_file():
            raise FileNotFoundError(asset)
        version = hashlib.sha256(asset.read_bytes()).hexdigest()[:16]
        portrait['src'] = 'https://aurai-game.invalid/bundled/' + portrait['asset'] + '?v=' + version
    resources_html = '\n'.join('<script type="application/aurai-resource" id="' + item['key'] + '">' + encoded(item) + '</script>' for item in resources)
    resources_html += '\n<script type="application/json" id="reference-index">' + encoded(documents) + '</script>'
    resources_html += '\n<script type="application/json" id="portrait-index">' + encoded(portraits) + '</script>'
    resources_html += '\n<script type="application/json" id="game-rules">' + encoded(rules) + '</script>'
    references = [{'key': d['key'], 'title': d['title']} for d in documents]
    references += [{'key': r['key'], 'title': r['title']} for r in resources if 'stateField' in r]
    reducer = '\n'.join((SOURCE / name).read_text(encoding='utf-8') for name in ['engine.js', 'operations.js', 'program.js', 'projection.js'])
    program = 'var rules=' + encoded(rules) + ';\nvar referenceIndex=' + encoded(references) + ';\n' + reducer
    ui = '\n'.join((SOURCE / name).read_text(encoding='utf-8') for name in ['state.js', 'guide.js', 'home.js', 'documents.js', 'characters.js', 'archive.js', 'navigation.js'])
    values = {'PROGRAM': '<script type="application/aurai-program">\n' + program + '</script>', 'STYLE': (SOURCE / 'style.css').read_text(encoding='utf-8'), 'RESOURCES': resources_html, 'UI': ui}
    output = (SOURCE / 'shell.html').read_text(encoding='utf-8')
    output = '<!-- Generated by scripts/build_animaline.py; edit miniapps/animaline modules. -->\n' + output
    for key, value in values.items():
        output = output.replace('{{' + key + '}}', value)
    if len(output.encode('utf-8')) > 4 * 1024 * 1024:
        raise ValueError('Animaline exceeds the miniapp 4 MiB source limit')
    target = ROOT / 'assets/miniapps/animaline.html'
    target.write_text(output, encoding='utf-8', newline='\n')
    # The standalone reducer remains useful when inspecting the game design.
    (ROOT / 'docs/animaline-program.js').write_text('// Generated by scripts/build_animaline.py; edit miniapps/animaline/program.js.\n' + program, encoding='utf-8')
    catalog_path = ROOT / 'assets/miniapps/catalog.json'
    catalog = json.loads(catalog_path.read_text(encoding='utf-8'))
    for entry in catalog:
        if entry['id'] == 'builtin.animaline':
            entry['version'] = hashlib.sha256(target.read_bytes()).hexdigest()
    catalog_path.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print('Built Animaline:', len(resources), 'lazy resources,', len(output.encode()), 'bytes')


if __name__ == '__main__':
    build()
