enum MessageAction {
  quickGrin,
  quickBeaming,
  quickRollingLaugh,
  quickKiss,
  quickPleading,
  quickSleepy,
  quickProud,
  quickScared,
  quickNauseated,
  quickDrooling,
  quickSneezing,
  quickPartyFace,
  quickSkull,
  quickAlien,
  quickSeeNoEvil,
  quickShush,
  quickZipMouth,
  quickYawn,
  quickSick,
  quickMelting,
  quickUpsideDown,
  quickWink,
  quickWave,
  quickFistBump,
  quickVictory,
  quickPointUp,
  quickWriting,
  quickFrog,
  quickRabbit,
  quickBear,
  quickTiger,
  quickDragon,
  quickButterfly,
  quickSnail,
  quickTurtle,
  quickShark,
  quickPizza,
  quickCake,
  quickMilkTea,
  quickCheers,
  quickSparkles,
  quickBomb,
  quickSob,
  quickTouched,
  quickEyeRoll,
  quickMindBlown,
  quickSalute,
  quickHandshake,
  quickPanda,
  quickFox,
  quickPopcorn,
  quickBrain,
  quickTrophy,
  quickHeartHands,
  quickDog,
  quickPenguin,
  quickCat,
  quickUnicorn,
  quickGhost,
  quickRobot,
  quickPoop,
  quickMelon,
  quickLemon,
  quickBeer,
  quickBrokenHeart,
  quickWiltedFlower,
  quickSleep,
  quickRainbow,
  quickFlower,
  quickGift,
  quickRocket,
  quickCoffee,
  quickDiamond,
  quickClover,
  quickIce,
  quickParty,
  quickBullseye,
  quickSmile,
  quickSurprised,
  quickSad,
  quickAngry,
  quickThinking,
  quickSweat,
  quickSpeechless,
  quickCool,
  quickClap,
  quickThanks,
  quickStrong,
  quickFire,
  quickHundred,
  quickHug,
  quickHeartEyes,
  quickLike,
  quickDislike,
  quickLove,
  quickLaugh,
  quickCelebrate,
  quickPlusOne,
  quickDone,
  quickReceived,
  quickViewing,
  quickQuestion,
  copy,
  select,
  edit,
  quote,
  recall,
  forward,
  fullscreen,
  statistics,
  history,
}

({String key, String text})? quickReplyForAction(MessageAction action) =>
    switch (action) {
      MessageAction.quickDislike => (key: 'dislike', text: '👎 点踩'),
      MessageAction.quickLove => (key: 'love', text: '❤️ 喜欢'),
      MessageAction.quickLaugh => (key: 'laugh', text: '😂 哈哈'),
      MessageAction.quickCelebrate => (key: 'celebrate', text: '🎉 庆祝'),
      MessageAction.quickLike => (key: 'like', text: '👍 点赞'),
      MessageAction.quickPlusOne => (key: 'plus_one', text: '+1 附议'),
      MessageAction.quickDone => (key: 'done', text: '✅ 完成'),
      MessageAction.quickReceived => (key: 'received', text: '👌 收到'),
      MessageAction.quickViewing => (key: 'viewing', text: '👀 在看'),
      MessageAction.quickQuestion => (key: 'question', text: '❓ 有疑问'),
      MessageAction.quickSmile => (key: 'smile', text: '😊 开心'),
      MessageAction.quickSurprised => (key: 'surprised', text: '😮 惊讶'),
      MessageAction.quickSad => (key: 'sad', text: '😢 难过'),
      MessageAction.quickAngry => (key: 'angry', text: '😡 生气'),
      MessageAction.quickThinking => (key: 'thinking', text: '🤔 思考'),
      MessageAction.quickSweat => (key: 'sweat', text: '😅 尴尬'),
      MessageAction.quickSpeechless => (key: 'speechless', text: '😑 无语'),
      MessageAction.quickCool => (key: 'cool', text: '😎 酷'),
      MessageAction.quickClap => (key: 'clap', text: '👏 鼓掌'),
      MessageAction.quickThanks => (key: 'thanks', text: '🙏 感谢'),
      MessageAction.quickStrong => (key: 'strong', text: '💪 加油'),
      MessageAction.quickFire => (key: 'fire', text: '🔥 火热'),
      MessageAction.quickHundred => (key: 'hundred', text: '💯 满分'),
      MessageAction.quickHug => (key: 'hug', text: '🤗 抱抱'),
      MessageAction.quickHeartEyes => (key: 'heart_eyes', text: '😍 心动'),
      MessageAction.quickRainbow => (key: 'rainbow', text: '🌈 彩虹'),
      MessageAction.quickFlower => (key: 'flower', text: '🌸 送花'),
      MessageAction.quickGift => (key: 'gift', text: '🎁 礼物'),
      MessageAction.quickRocket => (key: 'rocket', text: '🚀 起飞'),
      MessageAction.quickCoffee => (key: 'coffee', text: '☕ 喝杯咖啡'),
      MessageAction.quickDiamond => (key: 'diamond', text: '💎 珍贵'),
      MessageAction.quickClover => (key: 'clover', text: '🍀 好运'),
      MessageAction.quickIce => (key: 'ice', text: '🧊 冷静'),
      MessageAction.quickParty => (key: 'party', text: '🎊 欢庆'),
      MessageAction.quickBullseye => (key: 'bullseye', text: '🎯 说到点上'),
      MessageAction.quickPenguin => (key: 'penguin', text: '🐧 企鹅'),
      MessageAction.quickCat => (key: 'cat', text: '🐱 猫猫'),
      MessageAction.quickUnicorn => (key: 'unicorn', text: '🦄 独角兽'),
      MessageAction.quickGhost => (key: 'ghost', text: '👻 幽灵'),
      MessageAction.quickRobot => (key: 'robot', text: '🤖 机器人'),
      MessageAction.quickPoop => (key: 'poop', text: '💩 便便'),
      MessageAction.quickMelon => (key: 'melon', text: '🍉 吃瓜'),
      MessageAction.quickLemon => (key: 'lemon', text: '🍋 酸了'),
      MessageAction.quickBeer => (key: 'beer', text: '🍺 干杯'),
      MessageAction.quickBrokenHeart => (key: 'broken_heart', text: '💔 心碎'),
      MessageAction.quickWiltedFlower => (key: 'wilted_flower', text: '🥀 枯萎'),
      MessageAction.quickSleep => (key: 'sleep', text: '💤 困了'),
      MessageAction.quickDog => (key: 'dog', text: '🐶 狗头'),
      MessageAction.quickSob => (key: 'sob', text: '😭 大哭'),
      MessageAction.quickTouched => (key: 'touched', text: '🥹 感动'),
      MessageAction.quickEyeRoll => (key: 'eye_roll', text: '🙄 白眼'),
      MessageAction.quickMindBlown => (key: 'mind_blown', text: '🤯 震惊'),
      MessageAction.quickSalute => (key: 'salute', text: '🫡 敬礼'),
      MessageAction.quickHandshake => (key: 'handshake', text: '🤝 握手'),
      MessageAction.quickPanda => (key: 'panda', text: '🐼 熊猫'),
      MessageAction.quickFox => (key: 'fox', text: '🦊 狐狸'),
      MessageAction.quickPopcorn => (key: 'popcorn', text: '🍿 看戏'),
      MessageAction.quickBrain => (key: 'brain', text: '🧠 聪明'),
      MessageAction.quickTrophy => (key: 'trophy', text: '🏆 冠军'),
      MessageAction.quickHeartHands => (key: 'heart_hands', text: '🫶 比心'),
      MessageAction.quickSkull => (key: 'skull', text: '💀 笑死'),
      MessageAction.quickAlien => (key: 'alien', text: '👽 外星人'),
      MessageAction.quickSeeNoEvil => (key: 'see_no_evil', text: '🙈 没眼看'),
      MessageAction.quickShush => (key: 'shush', text: '🤫 嘘'),
      MessageAction.quickZipMouth => (key: 'zip_mouth', text: '🤐 保密'),
      MessageAction.quickYawn => (key: 'yawn', text: '🥱 打哈欠'),
      MessageAction.quickSick => (key: 'sick', text: '🤒 不舒服'),
      MessageAction.quickMelting => (key: 'melting', text: '🫠 融化'),
      MessageAction.quickUpsideDown => (key: 'upside_down', text: '🙃 倒着笑'),
      MessageAction.quickWink => (key: 'wink', text: '😉 眨眼'),
      MessageAction.quickWave => (key: 'wave', text: '👋 挥手'),
      MessageAction.quickFistBump => (key: 'fist_bump', text: '👊 碰拳'),
      MessageAction.quickVictory => (key: 'victory', text: '✌️ 耶'),
      MessageAction.quickPointUp => (key: 'point_up', text: '☝️ 注意'),
      MessageAction.quickWriting => (key: 'writing', text: '✍️ 记下了'),
      MessageAction.quickFrog => (key: 'frog', text: '🐸 青蛙'),
      MessageAction.quickRabbit => (key: 'rabbit', text: '🐰 兔兔'),
      MessageAction.quickBear => (key: 'bear', text: '🐻 小熊'),
      MessageAction.quickTiger => (key: 'tiger', text: '🐯 老虎'),
      MessageAction.quickDragon => (key: 'dragon', text: '🐉 龙'),
      MessageAction.quickButterfly => (key: 'butterfly', text: '🦋 蝴蝶'),
      MessageAction.quickSnail => (key: 'snail', text: '🐌 慢慢来'),
      MessageAction.quickTurtle => (key: 'turtle', text: '🐢 不着急'),
      MessageAction.quickShark => (key: 'shark', text: '🦈 鲨鱼'),
      MessageAction.quickPizza => (key: 'pizza', text: '🍕 披萨'),
      MessageAction.quickCake => (key: 'cake', text: '🎂 生日快乐'),
      MessageAction.quickMilkTea => (key: 'milk_tea', text: '🧋 奶茶'),
      MessageAction.quickCheers => (key: 'cheers', text: '🥂 庆功'),
      MessageAction.quickSparkles => (key: 'sparkles', text: '✨ 闪亮'),
      MessageAction.quickBomb => (key: 'bomb', text: '💣 炸了'),
      MessageAction.quickGrin => (key: 'grin', text: '😀 笑脸'),
      MessageAction.quickBeaming => (key: 'beaming', text: '😁 灿烂'),
      MessageAction.quickRollingLaugh => (key: 'rolling_laugh', text: '🤣 笑翻'),
      MessageAction.quickKiss => (key: 'kiss', text: '😘 亲亲'),
      MessageAction.quickPleading => (key: 'pleading', text: '🥺 可怜'),
      MessageAction.quickSleepy => (key: 'sleepy', text: '😴 睡着'),
      MessageAction.quickProud => (key: 'proud', text: '😤 不服'),
      MessageAction.quickScared => (key: 'scared', text: '😱 惊恐'),
      MessageAction.quickNauseated => (key: 'nauseated', text: '🤢 恶心'),
      MessageAction.quickDrooling => (key: 'drooling', text: '🤤 馋了'),
      MessageAction.quickSneezing => (key: 'sneezing', text: '🤧 感冒'),
      MessageAction.quickPartyFace => (key: 'party_face', text: '🥳 派对'),
      _ => null,
    };

const quickReplyOptions = [
  (MessageAction.quickPlusOne, '+1', '附议', 'plus_one'),
  (MessageAction.quickReceived, '👌', '收到', 'received'),
  (MessageAction.quickLike, '👍', '点赞', 'like'),
  (MessageAction.quickDislike, '👎', '点踩', 'dislike'),
  (MessageAction.quickDog, '🐶', '狗头', 'dog'),
  (MessageAction.quickLove, '❤️', '喜欢', 'love'),
  (MessageAction.quickLaugh, '😂', '哈哈', 'laugh'),
  (MessageAction.quickCelebrate, '🎉', '庆祝', 'celebrate'),
  (MessageAction.quickDone, '✅', '完成', 'done'),
  (MessageAction.quickViewing, '👀', '在看', 'viewing'),
  (MessageAction.quickQuestion, '❓', '疑问', 'question'),
  (MessageAction.quickSmile, '😊', '开心', 'smile'),
  (MessageAction.quickSurprised, '😮', '惊讶', 'surprised'),
  (MessageAction.quickSad, '😢', '难过', 'sad'),
  (MessageAction.quickAngry, '😡', '生气', 'angry'),
  (MessageAction.quickThinking, '🤔', '思考', 'thinking'),
  (MessageAction.quickSweat, '😅', '尴尬', 'sweat'),
  (MessageAction.quickSpeechless, '😑', '无语', 'speechless'),
  (MessageAction.quickCool, '😎', '酷', 'cool'),
  (MessageAction.quickClap, '👏', '鼓掌', 'clap'),
  (MessageAction.quickThanks, '🙏', '感谢', 'thanks'),
  (MessageAction.quickStrong, '💪', '加油', 'strong'),
  (MessageAction.quickFire, '🔥', '火热', 'fire'),
  (MessageAction.quickHundred, '💯', '满分', 'hundred'),
  (MessageAction.quickHug, '🤗', '抱抱', 'hug'),
  (MessageAction.quickHeartEyes, '😍', '心动', 'heart_eyes'),
  (MessageAction.quickRainbow, '🌈', '彩虹', 'rainbow'),
  (MessageAction.quickFlower, '🌸', '送花', 'flower'),
  (MessageAction.quickGift, '🎁', '礼物', 'gift'),
  (MessageAction.quickRocket, '🚀', '起飞', 'rocket'),
  (MessageAction.quickCoffee, '☕', '喝杯咖啡', 'coffee'),
  (MessageAction.quickDiamond, '💎', '珍贵', 'diamond'),
  (MessageAction.quickClover, '🍀', '好运', 'clover'),
  (MessageAction.quickIce, '🧊', '冷静', 'ice'),
  (MessageAction.quickParty, '🎊', '欢庆', 'party'),
  (MessageAction.quickBullseye, '🎯', '说到点上', 'bullseye'),
  (MessageAction.quickPenguin, '🐧', '企鹅', 'penguin'),
  (MessageAction.quickCat, '🐱', '猫猫', 'cat'),
  (MessageAction.quickUnicorn, '🦄', '独角兽', 'unicorn'),
  (MessageAction.quickGhost, '👻', '幽灵', 'ghost'),
  (MessageAction.quickRobot, '🤖', '机器人', 'robot'),
  (MessageAction.quickPoop, '💩', '便便', 'poop'),
  (MessageAction.quickMelon, '🍉', '吃瓜', 'melon'),
  (MessageAction.quickLemon, '🍋', '酸了', 'lemon'),
  (MessageAction.quickBeer, '🍺', '干杯', 'beer'),
  (MessageAction.quickBrokenHeart, '💔', '心碎', 'broken_heart'),
  (MessageAction.quickWiltedFlower, '🥀', '枯萎', 'wilted_flower'),
  (MessageAction.quickSleep, '💤', '困了', 'sleep'),
  (MessageAction.quickSob, '😭', '大哭', 'sob'),
  (MessageAction.quickTouched, '🥹', '感动', 'touched'),
  (MessageAction.quickEyeRoll, '🙄', '白眼', 'eye_roll'),
  (MessageAction.quickMindBlown, '🤯', '震惊', 'mind_blown'),
  (MessageAction.quickSalute, '🫡', '敬礼', 'salute'),
  (MessageAction.quickHandshake, '🤝', '握手', 'handshake'),
  (MessageAction.quickPanda, '🐼', '熊猫', 'panda'),
  (MessageAction.quickFox, '🦊', '狐狸', 'fox'),
  (MessageAction.quickPopcorn, '🍿', '看戏', 'popcorn'),
  (MessageAction.quickBrain, '🧠', '聪明', 'brain'),
  (MessageAction.quickTrophy, '🏆', '冠军', 'trophy'),
  (MessageAction.quickHeartHands, '🫶', '比心', 'heart_hands'),
  (MessageAction.quickSkull, '💀', '笑死', 'skull'),
  (MessageAction.quickAlien, '👽', '外星人', 'alien'),
  (MessageAction.quickSeeNoEvil, '🙈', '没眼看', 'see_no_evil'),
  (MessageAction.quickShush, '🤫', '嘘', 'shush'),
  (MessageAction.quickZipMouth, '🤐', '保密', 'zip_mouth'),
  (MessageAction.quickYawn, '🥱', '打哈欠', 'yawn'),
  (MessageAction.quickSick, '🤒', '不舒服', 'sick'),
  (MessageAction.quickMelting, '🫠', '融化', 'melting'),
  (MessageAction.quickUpsideDown, '🙃', '倒着笑', 'upside_down'),
  (MessageAction.quickWink, '😉', '眨眼', 'wink'),
  (MessageAction.quickWave, '👋', '挥手', 'wave'),
  (MessageAction.quickFistBump, '👊', '碰拳', 'fist_bump'),
  (MessageAction.quickVictory, '✌️', '耶', 'victory'),
  (MessageAction.quickPointUp, '☝️', '注意', 'point_up'),
  (MessageAction.quickWriting, '✍️', '记下了', 'writing'),
  (MessageAction.quickFrog, '🐸', '青蛙', 'frog'),
  (MessageAction.quickRabbit, '🐰', '兔兔', 'rabbit'),
  (MessageAction.quickBear, '🐻', '小熊', 'bear'),
  (MessageAction.quickTiger, '🐯', '老虎', 'tiger'),
  (MessageAction.quickDragon, '🐉', '龙', 'dragon'),
  (MessageAction.quickButterfly, '🦋', '蝴蝶', 'butterfly'),
  (MessageAction.quickSnail, '🐌', '慢慢来', 'snail'),
  (MessageAction.quickTurtle, '🐢', '不着急', 'turtle'),
  (MessageAction.quickShark, '🦈', '鲨鱼', 'shark'),
  (MessageAction.quickPizza, '🍕', '披萨', 'pizza'),
  (MessageAction.quickCake, '🎂', '生日快乐', 'cake'),
  (MessageAction.quickMilkTea, '🧋', '奶茶', 'milk_tea'),
  (MessageAction.quickCheers, '🥂', '庆功', 'cheers'),
  (MessageAction.quickSparkles, '✨', '闪亮', 'sparkles'),
  (MessageAction.quickBomb, '💣', '炸了', 'bomb'),
  (MessageAction.quickGrin, '😀', '笑脸', 'grin'),
  (MessageAction.quickBeaming, '😁', '灿烂', 'beaming'),
  (MessageAction.quickRollingLaugh, '🤣', '笑翻', 'rolling_laugh'),
  (MessageAction.quickKiss, '😘', '亲亲', 'kiss'),
  (MessageAction.quickPleading, '🥺', '可怜', 'pleading'),
  (MessageAction.quickSleepy, '😴', '睡着', 'sleepy'),
  (MessageAction.quickProud, '😤', '不服', 'proud'),
  (MessageAction.quickScared, '😱', '惊恐', 'scared'),
  (MessageAction.quickNauseated, '🤢', '恶心', 'nauseated'),
  (MessageAction.quickDrooling, '🤤', '馋了', 'drooling'),
  (MessageAction.quickSneezing, '🤧', '感冒', 'sneezing'),
  (MessageAction.quickPartyFace, '🥳', '派对', 'party_face'),
];
