enum MessageAction {
  quickDog,
  quickPenguin,
  quickCat,
  quickUnicorn,
  quickGhost,
  quickRobot,
  quickPoop,
  quickMelon,
  quickLemon,
  quickBeer,
  quickBrokenHeart,
  quickWiltedFlower,
  quickSleep,
  quickRainbow,
  quickFlower,
  quickGift,
  quickRocket,
  quickCoffee,
  quickDiamond,
  quickClover,
  quickIce,
  quickParty,
  quickBullseye,
  quickSmile,
  quickSurprised,
  quickSad,
  quickAngry,
  quickThinking,
  quickSweat,
  quickSpeechless,
  quickCool,
  quickClap,
  quickThanks,
  quickStrong,
  quickFire,
  quickHundred,
  quickHug,
  quickHeartEyes,
  quickLike,
  quickDislike,
  quickLove,
  quickLaugh,
  quickCelebrate,
  quickPlusOne,
  quickDone,
  quickReceived,
  quickViewing,
  quickQuestion,
  copy,
  select,
  edit,
  quote,
  recall,
  forward,
  fullscreen,
  statistics,
  history,
}

({String key, String text})? quickReplyForAction(MessageAction action) =>
    switch (action) {
      MessageAction.quickDislike => (key: 'dislike', text: '👎 点踩'),
      MessageAction.quickLove => (key: 'love', text: '❤️ 喜欢'),
      MessageAction.quickLaugh => (key: 'laugh', text: '😂 哈哈'),
      MessageAction.quickCelebrate => (key: 'celebrate', text: '🎉 庆祝'),
      MessageAction.quickLike => (key: 'like', text: '👍 点赞'),
      MessageAction.quickPlusOne => (key: 'plus_one', text: '+1 附议'),
      MessageAction.quickDone => (key: 'done', text: '✅ 完成'),
      MessageAction.quickReceived => (key: 'received', text: '👌 收到'),
      MessageAction.quickViewing => (key: 'viewing', text: '👀 在看'),
      MessageAction.quickQuestion => (key: 'question', text: '❓ 有疑问'),
      MessageAction.quickSmile => (key: 'smile', text: '😊 开心'),
      MessageAction.quickSurprised => (key: 'surprised', text: '😮 惊讶'),
      MessageAction.quickSad => (key: 'sad', text: '😢 难过'),
      MessageAction.quickAngry => (key: 'angry', text: '😡 生气'),
      MessageAction.quickThinking => (key: 'thinking', text: '🤔 思考'),
      MessageAction.quickSweat => (key: 'sweat', text: '😅 尴尬'),
      MessageAction.quickSpeechless => (key: 'speechless', text: '😑 无语'),
      MessageAction.quickCool => (key: 'cool', text: '😎 酷'),
      MessageAction.quickClap => (key: 'clap', text: '👏 鼓掌'),
      MessageAction.quickThanks => (key: 'thanks', text: '🙏 感谢'),
      MessageAction.quickStrong => (key: 'strong', text: '💪 加油'),
      MessageAction.quickFire => (key: 'fire', text: '🔥 火热'),
      MessageAction.quickHundred => (key: 'hundred', text: '💯 满分'),
      MessageAction.quickHug => (key: 'hug', text: '🤗 抱抱'),
      MessageAction.quickHeartEyes => (key: 'heart_eyes', text: '😍 心动'),
      MessageAction.quickRainbow => (key: 'rainbow', text: '🌈 彩虹'),
      MessageAction.quickFlower => (key: 'flower', text: '🌸 送花'),
      MessageAction.quickGift => (key: 'gift', text: '🎁 礼物'),
      MessageAction.quickRocket => (key: 'rocket', text: '🚀 起飞'),
      MessageAction.quickCoffee => (key: 'coffee', text: '☕ 喝杯咖啡'),
      MessageAction.quickDiamond => (key: 'diamond', text: '💎 珍贵'),
      MessageAction.quickClover => (key: 'clover', text: '🍀 好运'),
      MessageAction.quickIce => (key: 'ice', text: '🧊 冷静'),
      MessageAction.quickParty => (key: 'party', text: '🎊 欢庆'),
      MessageAction.quickBullseye => (key: 'bullseye', text: '🎯 说到点上'),
      MessageAction.quickPenguin => (key: 'penguin', text: '🐧 企鹅'),
      MessageAction.quickCat => (key: 'cat', text: '🐱 猫猫'),
      MessageAction.quickUnicorn => (key: 'unicorn', text: '🦄 独角兽'),
      MessageAction.quickGhost => (key: 'ghost', text: '👻 幽灵'),
      MessageAction.quickRobot => (key: 'robot', text: '🤖 机器人'),
      MessageAction.quickPoop => (key: 'poop', text: '💩 便便'),
      MessageAction.quickMelon => (key: 'melon', text: '🍉 吃瓜'),
      MessageAction.quickLemon => (key: 'lemon', text: '🍋 酸了'),
      MessageAction.quickBeer => (key: 'beer', text: '🍺 干杯'),
      MessageAction.quickBrokenHeart => (key: 'broken_heart', text: '💔 心碎'),
      MessageAction.quickWiltedFlower => (key: 'wilted_flower', text: '🥀 枯萎'),
      MessageAction.quickSleep => (key: 'sleep', text: '💤 困了'),
      MessageAction.quickDog => (key: 'dog', text: '🐶 狗头'),
      _ => null,
    };

const quickReplyOptions = [
  (MessageAction.quickPlusOne, '+1', '附议', 'plus_one'),
  (MessageAction.quickReceived, '👌', '收到', 'received'),
  (MessageAction.quickLike, '👍', '点赞', 'like'),
  (MessageAction.quickDislike, '👎', '点踩', 'dislike'),
  (MessageAction.quickDog, '🐶', '狗头', 'dog'),
  (MessageAction.quickLove, '❤️', '喜欢', 'love'),
  (MessageAction.quickLaugh, '😂', '哈哈', 'laugh'),
  (MessageAction.quickCelebrate, '🎉', '庆祝', 'celebrate'),
  (MessageAction.quickDone, '✅', '完成', 'done'),
  (MessageAction.quickViewing, '👀', '在看', 'viewing'),
  (MessageAction.quickQuestion, '❓', '疑问', 'question'),
  (MessageAction.quickSmile, '😊', '开心', 'smile'),
  (MessageAction.quickSurprised, '😮', '惊讶', 'surprised'),
  (MessageAction.quickSad, '😢', '难过', 'sad'),
  (MessageAction.quickAngry, '😡', '生气', 'angry'),
  (MessageAction.quickThinking, '🤔', '思考', 'thinking'),
  (MessageAction.quickSweat, '😅', '尴尬', 'sweat'),
  (MessageAction.quickSpeechless, '😑', '无语', 'speechless'),
  (MessageAction.quickCool, '😎', '酷', 'cool'),
  (MessageAction.quickClap, '👏', '鼓掌', 'clap'),
  (MessageAction.quickThanks, '🙏', '感谢', 'thanks'),
  (MessageAction.quickStrong, '💪', '加油', 'strong'),
  (MessageAction.quickFire, '🔥', '火热', 'fire'),
  (MessageAction.quickHundred, '💯', '满分', 'hundred'),
  (MessageAction.quickHug, '🤗', '抱抱', 'hug'),
  (MessageAction.quickHeartEyes, '😍', '心动', 'heart_eyes'),
  (MessageAction.quickRainbow, '🌈', '彩虹', 'rainbow'),
  (MessageAction.quickFlower, '🌸', '送花', 'flower'),
  (MessageAction.quickGift, '🎁', '礼物', 'gift'),
  (MessageAction.quickRocket, '🚀', '起飞', 'rocket'),
  (MessageAction.quickCoffee, '☕', '喝杯咖啡', 'coffee'),
  (MessageAction.quickDiamond, '💎', '珍贵', 'diamond'),
  (MessageAction.quickClover, '🍀', '好运', 'clover'),
  (MessageAction.quickIce, '🧊', '冷静', 'ice'),
  (MessageAction.quickParty, '🎊', '欢庆', 'party'),
  (MessageAction.quickBullseye, '🎯', '说到点上', 'bullseye'),
  (MessageAction.quickPenguin, '🐧', '企鹅', 'penguin'),
  (MessageAction.quickCat, '🐱', '猫猫', 'cat'),
  (MessageAction.quickUnicorn, '🦄', '独角兽', 'unicorn'),
  (MessageAction.quickGhost, '👻', '幽灵', 'ghost'),
  (MessageAction.quickRobot, '🤖', '机器人', 'robot'),
  (MessageAction.quickPoop, '💩', '便便', 'poop'),
  (MessageAction.quickMelon, '🍉', '吃瓜', 'melon'),
  (MessageAction.quickLemon, '🍋', '酸了', 'lemon'),
  (MessageAction.quickBeer, '🍺', '干杯', 'beer'),
  (MessageAction.quickBrokenHeart, '💔', '心碎', 'broken_heart'),
  (MessageAction.quickWiltedFlower, '🥀', '枯萎', 'wilted_flower'),
  (MessageAction.quickSleep, '💤', '困了', 'sleep'),
];
