const skillIcons = {
  'skill': '技能',
  'discover': '发现',
  'conversation': '会话',
  'miniapp': '小程序',
  'tools': '工具',
  'data': '数据',
  'task': '任务',
  'phone': '手机',
  'settings': '设置',
  'browser': '浏览器',
  'window': '窗口',
  'group': '群聊',
  'camera': '相机',
  'clipboard': '剪贴板',
  'calculator': '计算器',
  'clock': '时钟',
  'battery': '电池',
  'download': '下载',
  'checklist': '清单',
  'news': '新闻',
  'search': '搜索',
  'calendar': '日历',
  'notification': '通知',
  'file': '文件夹',
  'code': '代码',
  'network': '网络',
  'food': '美食',
  'shopping': '购物',
  'location': '地点',
  'photo': '图片',
  'image-search': '图片搜索',
  'app-search': '应用搜索',
  'music': '音乐',
  'audio': '音频',
  'video': '视频',
  'chart': '统计',
  'translate': '翻译',
  'mail': '邮件',
  'health': '健康',
  'travel': '旅行',
  'memory': '记忆',
  'personalization': '个性化',
  'profile': '个人信息',
  'contacts': '通讯录',
  'game': '手柄',
  'balance': '余额',
  'appearance': '夜间模式',
  'model': '模型',
  'device': '设备能力',
  'filter': '筛选',
  'pin': '置顶',
  'unpin': '取消置顶',
  'rename': '编辑',
  'archive': '归档',
  'unarchive': '取消归档',
  'delete': '删除',
  'compose': '新建会话',
  'question': '提问',
  'close': '关闭',
  'check': '完成',
  'gallery': '相册',
  'document': '文档',
  'create-file': '创建文件',
  'pdf': 'PDF',
  'presentation': '演示文稿',
  'package': '压缩包',
  'permission': '授权',
  'forward': '转发',
  'quote': '引用',
  'select-text': '选择文本',
  'star': '收藏',
  'mark': '书签',
  'copy': '复制',
  'announcement': '公告',
  'recall': '撤回',
  'retry': '重试',
  'share-file': '分享文件',
  'word': 'Word 文档',
  'excel': '电子表格',
  'ebook': '电子书',
  'terminal': '终端',
  'database': '数据库',
  'api': '接口',
  'cloud': '云端',
  'link': '链接',
  'lock': '安全',
  'key': '密钥',
  'robot': '机器人',
  'bug': '调试',
  'automation': '自动化',
  'palette': '画板',
  'science': '实验',
  'brain': '思考',
};

const _skillIconChoiceOrder = [
  'skill',
  'discover',
  'conversation',
  'compose',
  'group',
  'miniapp',
  'tools',
  'task',
  'search',
  'question',
  'robot',
  'brain',
  'settings',
  'data',
  'model',
  'memory',
  'personalization',
  'profile',
  'contacts',
  'device',
  'permission',
  'network',
  'phone',
  'browser',
  'window',
  'terminal',
  'code',
  'database',
  'api',
  'cloud',
  'link',
  'lock',
  'key',
  'automation',
  'bug',
  'file',
  'document',
  'word',
  'excel',
  'pdf',
  'presentation',
  'ebook',
  'package',
  'create-file',
  'share-file',
  'download',
  'clipboard',
  'photo',
  'image-search',
  'camera',
  'music',
  'audio',
  'video',
  'palette',
  'notification',
  'mail',
  'announcement',
  'forward',
  'quote',
  'select-text',
  'copy',
  'recall',
  'calendar',
  'clock',
  'checklist',
  'news',
  'pin',
  'unpin',
  'rename',
  'archive',
  'delete',
  'star',
  'mark',
  'filter',
  'check',
  'calculator',
  'battery',
  'chart',
  'translate',
  'location',
  'travel',
  'shopping',
  'food',
  'health',
  'science',
  'game',
  'appearance',
  'balance',
  'app-search',
];

final skillIconChoices = {
  for (final name in _skillIconChoiceOrder) name: skillIcons[name]!,
};
